### ISSUE TITLE
FCOM related stuff

### ISSUE THREAD

**Issue by Dredd893** [loot/oblivion#111]
Hello everyone.

1. Fcom convergence should have the tag `Actors.AIPackagesForceAdd`, but it missing from both LOOT and BOSS. [Source](https://www.nexusmods.com/oblivion/mods/12249). Specifically, check: "Quick Bash Check Guide for Wrye Bash 287" Import Actors: AIPackages - All FCOM mods and UOP checked. Tag FCOM_Convergence.esp with Actors.AIPackagesForceAdd.
- [x] Add bash tag `Actors.AIPackagesForceAdd` to `FCOM_Convergence.esp`.

2. Request to add `TNR - Shivering isles.esp` CRC: E04586F3. Note: when used with FCOM, it should be imported in the patch and then deactivated.
- [x] Remove bash tag `NoMerge` from `TNR - Shivering isles.esp` when using FCOM.

3. `Mart's Monster Mod - Additional Enemy NPC Vars.esp` The .esp is already there, but inside the extended load order for FCOM it is recommended not to use it. I wonder: is it due to the cpu load, or because you simply shouldn't use it with FCOM? Not all Mart's monster mod plugins can be used.
 - [x] Add FCOM to `Mart's Monster Mod - Additional Enemy NPC Vars.esp` inc list.

4. `FCOM_safer roads.esp` The .esp is already there, but I would add a note: it can't be used with nor the spawn plugins from MMM nor the one from FCOM. How can I say so? There is a image I saved from Gamesas: https://ibb.co/BfwBRn8 I think the same note should be added for spawns .esps (currently: FCOM_Spawnratesreduced.esp, FCOM_spawnratesslightlyreduced.esp, FCOM_spawnratesstronger.esp)
 - [x] Add Already in FCOM Spawn Rates ESPs message to FCOM_SaferRoads.esp.

5. `Fcom_lessreaversingate.esp` On the fcom webpage it is written:  This option reduces the Reaver spawn counts in Gate realms only. Can be used with MMM - Less Reavers.esp to get a greater overall reduction in their spawn rate. Should this claim be investigated?

6. `Fran_Lv30Item_Maltz.esp` According to the extended guide, you don't need any patch. And actually it is confirmed even by the FCOM_optionaladdons, where the LV30_item maltz is mentioned having no need for a FCOM patch. But this [plugin](https://www.nexusmods.com/oblivion/mods/46926) was released, It's not clear if it is actually needed.

7. Did anyone check the difference between `more wilderness life.esp` and `more wilderness life no gates.esp`? Because for `More wilderness life.esp` it is suggested cleaning, while it is not for `more wilderness life no gates.esp`. Note: is it sure that these plugins have to be cleaned? BOSS says ITM are intentional. Who checked they were not? Same can be said for: `Mart's monster mod.esm`, `Mart's city defences.esp`, `Martigen shivering isles.esp`.

8. `Francesco's Creatures and Items Resources.esp` is not needed. Note to be added: Remove it, and Francesco's Bsa should be renamed.
- [x] Add message to rename `Francesco's Creatures and Items Resources.bsa` to `FCOM_Convergence_FraNewItems.bsa`

9. [Always Transcendent Sigil Stones](https://www.nexusmods.com/oblivion/mods/32374) `SigilStonesAlwaysTranscendent.esp`
- [x] Add bash tag suggestions. `Delev`, `Relev`.

10. `unleveled-rewards.esp` [Unleveled Rewards](https://www.nexusmods.com/oblivion/mods/48049)
- [x] Add bash tag suggestions. `Delev`, `Relev`.

**Comment by Ortham** [comment]
I've moved this to the oblivion repo as it's oblivion-specific.

**Comment by MacSplody** [comment]
>     1. Does anyone know how can I improve the formatting of the post?

@Dredd893 There are some format options available when editing.

![image](https://user-images.githubusercontent.com/1944639/76160054-95e5cd00-611e-11ea-95c2-8f4d05301383.png)

& there are also cheatsheets for github flavoured markdown.
https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet
