### ISSUE TITLE
New tags for Oblivion mods

### ISSUE THREAD

**Issue by Dredd893** [loot/oblivion#112]
In the nexus, there is a guy publishing a lot of files containing new tags for mods. Should these be investigated?

**Comment by Ortham** [comment]
I've moved this to the oblivion repo as it's oblivion-specific.

**Comment by Sabre142** [comment]
Author of that utility here. A few reasons I keep them there as of now:

1. I'm a bit lazy and find it easier to upload things there
2. There have been a couple cases of problems arising from a seemingly appropriate tag or two, when they for some reason didn't mesh well with other mods. Placing them in the LOOT masterlist would subject everyone to those errors should they ever happen to arise again
3. Tags work differently in PBash and CBash. Take NoMerge for example which barely functions in CBash. That tag is necessary for some mods to work correctly, like Colored Quests. But if I add that to the masterlist, anyone using CBash won't be able to get the mod working.
4. I'm not sure some mod authors would be happy if I add new tags to their mods in the masterlist, so I keep it to my own corner for now

That said, I might in the future add new tags like Text to a lot of mods that need it in the masterlist.

**Comment by MacSplody** [comment]
I'm going to test these ones for DLC & Unofficial patches.

**`Unofficial Oblivion Patch.esp`**
Actors.Spells, C.RecordFlags, Graphics, Invent.Count, R.Description, Roads, Sound, SpellStats, Text

**`Unofficial Shivering Isles Patch.esp`**
Actors.Skeleton, Actors.Spells, C.Music, Graphics, NPC.Class, Roads, Sound, SpellStats, Text

**`DLCOrrery.esp`**
C.Light, Sound

**`DLCOrrery - Unofficial Patch.esp`**
Graphics, SpellStats

**`DLCVileLair - Unofficial Patch.esp`**
Actors.ACBS, Actors.AIData, Actors.AIPackages, C.Water, SpellStats, Stats, Text

**`DLCMehrunesRazor.esp`**
Factions

**`DLCMehrunesRazor - Unofficial Patch.esp`**
Graphics, Text

**`DLCSpellTomes - Unofficial Patch.esp`**
SpellStats, Text

**`DLCThievesDen.esp`**
C.Climate, C.Owner, C.Water, C.Music, Invent, Names

**`DLCThievesDen - Unofficial Patch.esp`**
Invent, Scripts, Text

**`DLCBattlehornCastle.esp`**
Sound

**`DLCBattlehornCastle - Unofficial Patch.esp`**
Actors.ACBS, Actors.AIPackages, Graphics, Names, Stats, Text

**`DLCFrostcrag.esp`**
~C.Regions~, Sound

**`DLCFrostcrag - Unofficial Patch.esp`**
Scripts, Sound, SpellStats

**`Knights.esp`**
Names

**`Knights - Unofficial Patch.esp`**
Actors.AIData, Actors.Stats, C.Name, Graphics, Invent, NPC.Class, Scripts, Sound, SpellStats, Stats, Text

**Comment by CptMcSplody** [comment]
`[cq]AdvancedFightersQuests.esp`
- [ ] Graphics
- [ ] NoMerge

`[cq]AdvancedMagesQuests.esp`
- [ ] Graphics
- [ ] NoMerge

`[cq]ColoredQuests.esp`
- [ ] Graphics
- [ ] NoMerge

`[cq]GuildAdvancement.esp`
- [ ] Graphics
- [ ] NoMerge

`[cq]QuestsoftheNine.esp`
- [ ] Graphics
- [ ] NoMerge

`[cq]ShiveringQuests.esp`
- [ ] Graphics
- [ ] NoMerge

`A Dog for Bhisha.esp`
- [ ] Factions

`All Natural.esp`
- [ ] Graphics

`All Natural - SI.esp`
- [ ] Graphics

`All Natural - Real Lights.esp`
- [ ] C.Climate
- [ ] Sound
- [ ] Stats

`Alluring Wine Bottles.esp`
- [ ] -MustBeActiveIfImported
- [ ] NoMerge

`Alternative Start by Robert Evrae.esp`
- [ ] Names
- [ ] SpellStats

`An Unexpected Company.esp`
- [ ] Graphics
- [ ] Names

`AoG - Greed Arena.esp`
- [ ] Actors.ACBS
- [ ] Actors.AIData
- [ ] Actors.AIPackages
- [ ] Actors.Spells
- [ ] Actors.Stats
- [ ] NPC.Class

`Av Latta Magicka - Birthsigns.esp`
- [ ] SpellStats
- [ ] Text

`Av Latta Magicka - Potion Rebalance.esp`
- [ ] Names
- [ ] Stats

`BalancedMagic.esp`
- [ ] Factions
- [ ] Scripts

`Better Abandoned House.esp`
- [ ] Names

`Better Cities Full.esp`
- [ ] Actors.AIPackages
- [ ] Actors.Spells
- [ ] C.Name
- [ ] C.Owner
- [ ] C.RecordFlags
- [ ] Graphics
- [ ] Invent
- [ ] Names
- [ ] Scripts

`Better Dark Brotherhood Sanctuary.esp`
- [ ] Actors.ACBS
- [ ] Actors.AIPackages
- [ ] Actors.Stats
- [ ] C.Light
- [ ] Factions
- [ ] Graphics
- [ ] Invent

`Better Dungeons.esp`
- [ ] Actors.ACBS
- [ ] Actors.Spells
- [ ] C.Name
- [ ] Graphics
- [ ] Invent
- [ ] Names
- [ ] Sound

`Better Wine SI.esp`
- [ ] Graphics
- [ ] NoMerge

`bgBalancingEVCore.esp`
- [ ] Names
- [ ] Text

`bgMagicBonus.esp`
- [ ] Names
- [ ] SpellStats

`bgMagicEV.esp`
- [ ] Graphics
- [ ] Sound
- [ ] SpellStats

`bgMagicEVAddEnVar.esp`
- [ ] Delev

`bgMagicEVAddEnVarNoSI.esp`
- [ ] Delev

`bgMagicEVNoSorting.esp`
- [ ] Names
- [ ] SpellStats

`bgMagicEVNoSpellLight.esp`
- [ ] Graphics

`bgMagicEVPaperChase.esp`
- [ ] Scripts

`bgMagicEVShader.esp`
- [ ] -NoMerge

`bgMagicEVStartspells.esp`
- [ ] SpellStats

`bgMagicEVStartspellsNoSorting.esp`
- [ ] Names
- [ ] SpellStats

`bgMagicShaderLifeDetect.esp`
- [ ] Graphics

`Birthsigns Expanded.esp`
- [ ] Text

`Book Jackets Oblivion - BP.esp`
- [ ] Graphics
- [ ] Names
- [ ] Stats
- [ ] Text

`Book Jackets Oblivion.esp`
- [ ] Graphics
- [ ] Names
- [ ] Stats
- [ ] Text

`Casual Conjurers.esp`
- [ ] Invent

`CM_Better Wine_SI.esp`
- [ ] Graphics
- [ ] NoMerge

`Cobl Glue.esp`
- [ ] C.Owner
- [ ] C.RecordFlags
- [ ] Stats

`Cobl Tweaks - OOO.esp`
- [ ] Names

`Cobl Tweaks - SI.esp`
- [ ] Actors.ACBS
- [ ] Actors.DeathItem
- [ ] Invent
- [ ] Relev
- [ ] Scripts

`Colorful Clothing - Middleclass.esp`
- [ ] Delev

`Creature Diversity.esp`
- [ ] Actors.Spells
- [ ] Graphics

`DaedraShrinesProddedWithAStick.esp`
- [ ] Actors.AIPackages
- [ ] Invent

`Dahyka's Vanilla Racial and Birthsign Tweaksv2.2.esp`
- [ ] Names
- [ ] R.AddSpells
- [ ] R.Skills
- [ ] SpellStats
- [ ] Text

`Devastation of Kvatch - Kvatch only.esp`
- [ ] Invent

`Devastation of Kvatch Redux.esp`
- [ ] Actors.ACBS
- [ ] Invent
- [ ] Names

`Devastation of Kvatch.esp`
- [ ] Invent

`DLCSpellTomes-No Attack.esp`
- [ ] Actors.AIPackages

`DLCThievesDen - BarterForUpgrd.esp`
- [ ] Actors.ACBS
- [ ] Actors.AIData
- [ ] Stats

`DoK - Kvatch only - Scattered Weapons.esp`
- [ ] Invent

`DoK - Scattered Weapons.esp`
- [ ] Invent

`Enhanced Vegetation [100%].esp`
- [ ] Graphics

`Enhanced Vegetation [110%].esp`
- [ ] Graphics

`Enhanced Vegetation [125%].esp`
- [ ] Graphics

`Enhanced Vegetation [150%].esp`
- [ ] Graphics

`Enhanced Water v2.0 HD.esp`
- [ ] C.Water

`Enhanced Water v2.0 ND.esp`
- [ ] C.Water

`EVE_StockEquipmentReplacer.esp`
- [ ] Stats

`Even More Sensible Grammar.esp`
- [ ] Text

`Finger of the Mountain Rebalanced.esp`
- [ ] SpellStats

`Generic Name Overhaul.esp`
- [ ] Names

`GhettoWaterfront.esp`
- [ ] Relations

`GhettoWaterfrontLight.esp`
- [ ] Relations

`Give Me My Shader Effects.esp`
- [ ] Actors.Spells

`GlowingSewerZombies.esp`
- [ ] Relations

`GMBirthsignsRebalance.esp`
- [ ] Text

`GMRacesRebalance.esp`
- [ ] Actors.ACBS
- [ ] Actors.Spells
- [ ] R.Attributes-F
- [ ] R.Attributes-M
- [ ] R.ChangeSpells
- [ ] R.Description
- [ ] R.Relations
- [ ] R.Skills
- [ ] Text

`GOSH.esp`
- [ ] Sound

`GOSH Region Ambiance.esp`
- [ ] Sound

`Harvest [Flora] - DLCFrostcrag.esp`
- [ ] Graphics
- [ ] Scripts

`Harvest [Flora] - DLCVileLair.esp`
- [ ] Graphics
- [ ] Scripts

`Immersive Weapons.esp`
- [ ] Graphics
- [ ] Invent

`Improved Fires and Flames - Increased Sound.esp`
- [ ] Sound

`ImprovedMraajDar.esp`
- [ ] Actors.ACBS
- [ ] Actors.AIData
- [ ] Invent

`Instruments of Cyrodiil.esp`
- [ ] Invent

`Jov'sMagesGloves.esp`
- [ ] Actors.AIData

`Kart Hair Replace v01.esp`
- [ ] Graphics

`Knightly Orders for Cities - KR Patch.esp`
- [ ] Graphics
- [ ] Invent

`Knightly Orders for Cities.esp`
- [ ] Graphics
- [ ] Invent

`Knights - Cobl.esp`
- [ ] Actors.ACBS
- [ ] Actors.AIData
- [ ] Actors.Stats
- [ ] C.Music
- [ ] Factions

`KOTNPokedWithAStick.esp`
- [ ] Actors.AIPackages
- [ ] Factions

`Kragenir's Death Quest.esp`
- [ ] Invent

`Kvatch Rebuilt.esp`
- [ ] Factions
- [ ] Relations

`Legion Armor Revised Classic.esp`
- [ ] Graphics
- [ ] Names

`LessStaticNPCs.esp`
- [ ] Actors.ACBS
- [ ] Actors.AIPackages
- [ ] Actors.Stats
- [ ] Factions
- [ ] Invent

`LittleShops.esp`
- [ ] Invent

`lLet there be Flowers.esp`
- [ ] Graphics

`Lost Sorceries of the Ayleids.esp`
- [ ] SpellStats

`Magic Visuals Overhaul.esp`
- [ ] Graphics

`MannimarcoRevisited UOP Patch.esp`
- [ ] C.Climate
- [ ] Text

`MannimarcoRevisited.esp`
- [ ] C.Name
- [ ] C.Water
- [ ] NpcFaces
- [ ] Stats
- [ ] Text

`MannimarcoRevisitedOOO.esp`
- [ ] Names
- [ ] Sound
- [ ] Stats

`Merged DLCs - OOO.esp`
- [ ] Actors.ACBS
- [ ] Delev
- [ ] Factions
- [ ] Invent
- [ ] Names
- [ ] Stats

`MidasSpells.esp`
- [ ] Stats

`MinimalMagicEffects.esp`
- [ ] Graphics

`MinimalMagicEffectsLAME.esp`
- [ ] Graphics

`More Magical Mages Guilds Clean.esp`
- [ ] C.Light

`More Magical Mages Guilds.esp`
- [ ] C.Light

`More Sensible Grammar.esp`
- [ ] Text

`Myserious Bear's Epic Necromancy.esp`
- [ ] Actors.ACBS
- [ ] Actors.Stats
- [ ] Invent
- [ ] Names
- [ ] NpcFaces
- [ ] Relations
- [ ] Scripts
- [ ] Sound

`No More Wild Goose Chases.esp`
- [ ] Invent
- [ ] Scripts

`NPC Hair Matches Beard.esp`
- [ ] NpcFaces
- [ ] NoMerge

`Oblivion Character Overhaul Hair Edition.esp`
- [ ] Graphics
- [ ] Names

`Oblivion Citadel Door Fix.esp`
- [ ] Graphics

`Oblivion Uncut.esp`
- [ ] Actors.Spells
- [ ] Graphics
- [ ] Relations
- [ ] Sound
- [ ] SpellStats
- [ ] Text

`Oblivion_Character_Overhaul.esp`
- [ ] Body-Size-M

`Oghma Infinium Crash Fix.esp`
- [ ] Scripts

`OMOBS_SI.esp`
- [ ] Names
- [ ] Stats

`One of a Kind Weapons.esp`
- [ ] Graphics

`OOO I&A - OOOExtended Difficulty Adjustments.esp`
- [ ] Graphics
- [ ] Invent
- [ ] Names
- [ ] Sound
- [ ] SpellStats
- [ ] Stats

`OOO Improvements and Additions - Shivering Isles.esp`
- [ ] Actors.Spells
- [ ] Delev
- [ ] Invent
- [ ] Names
- [ ] SpellStats

`OOO Improvements and Additions.esp`
- [ ] Creatures.Blood
- [ ] Relations
- [ ] Sound
- [ ] Text

`OOO-Rebalanced.esp`
- [ ] Names

`OOOExtended.esp`
- [ ] Actors.AIPackages
- [ ] C.Name
- [ ] C.RecordFlags
- [ ] Creatures.Blood
- [ ] Factions
- [ ] R.AddSpells
- [ ] Relations
- [ ] SpellStats
- [ ] Text

`OOOShiveringIsles.esp`
- [ ] C.Name
- [ ] C.Owner
- [ ] Sound
- [ ] Text

`OPW.esp`
- [ ] Stats

`Oscuro's_Oblivion_Overhaul - Knights of Nine.esp`
- [ ] Actors.Spells
- [ ] Factions
- [ ] Invent
- [ ] Stats

`RandomRoadEncounters.esp`
- [ ] Actors.ACBS
- [ ] Relations
- [ ] SpellStats

`RandomRoadEncountersLeveledLists.esp`
- [ ] Actors.ACBS
- [ ] Relations
- [ ] SpellStats

`Rathunas01.esp`
- [ ] C.Water
- [ ] Sound

`ReclaimSancreTor.esp`
- [ ] Invent
- [ ] Roads

`Reworked Race Relations.esp`
- [ ] R.Relations

`Secrets-UL edition.esp`
- [ ] Invent

`Secrets.esp`
- [ ] Invent

`SewerZombies.esp`
- [ ] Relations

`ShadierSam.esp`
- [ ] Invent
- [ ] Stats

`Skyrimized Water HD BLUE eng.esp`
- [ ] C.Water

`Skyrimized Water HD BLUE ita.esp`
- [ ] C.Water

`Skyrimized Water HD eng.esp`
- [ ] C.Water

`Skyrimized Water HD ita.esp`
- [ ] C.Water

`StrongerHindaril.esp`
- [ ] Actors.ACBS
- [ ] Actors.Spells
- [ ] Actors.Stats
- [ ] Invent

`SupremeMagicka.esp`
- [ ] Actors.Spells
- [ ] Sound
- [ ] SpellStats
- [ ] Stats

`Tales of Cyrodiil.esp`
- [ ] Names

`tbskGuardsFeatures OOO Patch.esp`
- [ ] Actors.ACBS
- [ ] Actors.Stats
- [ ] Factions
- [ ] Invent
- [ ] NPC.Class

`tbskGuardsFeatures.esp`
- [ ] Actors.ACBS
- [ ] Actors.Stats
- [ ] Factions
- [ ] Invent
- [ ] NPC.Class

`TRAP.esp`
- [ ] Actors.ACBS
- [ ] Actors.Spells
- [ ] Actors.Stats
- [ ] SpellStats

`Unique Landscapes.esp`
- [ ] C.Regions

`UniqueBirthsigns.esp`
- [ ] Names
- [ ] Text

`Vampire Power - Hindaril.esp`
- [ ] Actors.CombatStyle
- [ ] Actors.Spells
- [ ] Invent

`Vampire Power - Light of Day.esp`
- [ ] Actors.DeathItem
- [ ] Actors.Spells
- [ ] Factions
- [ ] Invent

`Vampire Power.esp`
- [ ] Graphics
- [ ] SpellStats

`VanillaCombatEnhanced.esp`
- [ ] SpellStats

`Variant Vagabonds.esp`
- [ ] Names

`WaterFPS.esp`
- [ ] C.Water

`Weapon Expansion Pack for Oblivion Nthusiasts.esp`
- [ ] Text

`Weapons Of Morrowind.esp`
- [ ] Delev

`xulBrenaRiverRavine.esp`
- [ ] C.Regions

**Comment by sibir-ine** [comment]
>     3. Tags work differently in PBash and CBash. Take NoMerge for example which barely functions in CBash. That tag is necessary for some mods to work correctly, like Colored Quests. But if I add that to the masterlist, anyone using CBash won't be able to get the mod working.

Just FYI, CBash has been officially deprecated as of 307 & removed as of 308 Beta 1 if that changes anything.

**Comment by MacSplody** [comment]
Moving to https://github.com/loot/oblivion/issues/653
