### ISSUE TITLE
Alias repeated messages

### ISSUE THREAD

**Issue by WrinklyNinja** [loot/oblivion#12]
Similar to my recent commits for the Skyrim, Fallout 3 and Fallout: New Vegas masterlists, I'll be going through the Oblivion masterlist and replacing repeated messages by aliases to common message anchors.

### Repeated Messages

- [x] `A modding esm - do not use in game, deactivate.`
- [x] `This needs to load directly after Oblivion.esm to avoid landscape issues caused by a failure by the mod author to use TES4Gecko''s "Move Worldspaces" function.`
- [ ] `If not using Wrye Bash load this later (though then it will override some things).`
- [x] Various `Sensual Walks` update messages.
- [x] `Use Wrye Bash Bashed Patch tweak instead.`
  - `Recommend removing if using Wrye Bash. A tweak for this exists in "Tweak Settings".`
  - `If using Wrye Bash use the bashed patch tweak instead.`
- [x] `Outdated. When using Francesco''s and/or FCOM, use the non-MOBS version of this patch and the standalone MOBS/OMOBS mods.`
  - `Use Standalone MOBS if using Frans or OMOBS if using FCOM/OOO. Both versions can be found [here](http://www.nexusmods.com/oblivion/mods/28537)`
- [x] `This mod is incompatible with weather mods.`
- [x] `Original mod is heavily bugged. Make sure you are using Ryu Doppler''s fixed version.`
  - `Outdated. Update to Ryu Doppler''s fixed Natural Weather.`
- [x] `Not compatible with OOO. OOO contains a similar mod.`
  - `Not compatible with OOO. Already included in OOO.`
- [ ] `Probably not compatible with OOO. Untested.`
- [ ] `Make sure to install the additional mods (listed in the readme).`
- [x] `Requires: Shivering Isles` - the `DLCShiveringIsles.esp` plugin is a dummy so may not be present in all installs, so it can't be turned into a `req` entry.
- [x] `Requires: OBSE` for various versions of OBSE. Some of these are repeated.
- [x] `Requires: Cobl.`
- [x] `Move this after OOO if you desire initial city map markers a la vanilla.`
- [x] `Don''t use hotkeys to change Warcry-style ''set'' equipment. Game bug.`
- [x] `Consider updating to the newer [Armamentarium Complete](http://www.nexusmods.com/oblivion/mods/18417) version.`
- [x] `Make sure to load an overhaul or something after. Or manually rename the cells that this edits.`
- [x] `Delete. Use FCOM_RealSwords instead.`
- [x] `Requires Wrye Bash for compatibility with overhaul mods like OOO/MMM/Fran''s.`
- [x] `Delete. Already integrated into FCOM, MMM, OOO or other FCOM components.`
  - `Incompatible with MMMforOOO/FCOM. Already integrated.`
  - `Remove this. Do not use with OOO/FCOM.`
  - `Delete. Already integrated into FCOM.`
  - `Delete. Not needed with FCOM.`
  - `Delete. Not compatible with FCOM.`
  - `Delete. Not compatible with FCOM. Use cOMbo plugin instead.`
- [x] `Should not be used. Delete. Reinstall Fran''s and select "Separate Files" when the option is presented.`
- [x] `Avoid using Potion Belt and KD Circlets at the same time. Character can wear belt or circlet, not both.`
- [x] `Don''t use with the FULL version of OOO, already included.`
  - `Will work with OOO ''light'' but is not compatible with the ''full'' installation of OOO.`
- [x] `Included in OOO. Remove unless you want to lose OOO''s container traps, security rebalance and lock bashing features (so you can use other mods for those).`
- [x] `Obsolete. Remove this and install FCOM.`
- [x] `Not recommended. Not fully tested with FCOM and creatures from other FCOM related mods may not appear.`
- [x] `Consider using ''FCOM_SpawnRatesReduced.esp'', ''FCOM_SpawnRatesSlightlyReduced.esp'' or ''FCOM_SpawnRatesStronger.esp'' instead.`
- [x] `Modular development plugin. Do not use with ''TIE In - FCOM Convergence.esp''.`
- [x] `Not recommended. Kept for development purposes only.` - there are a few other "modding only" messages.
- [x] `Incompatible with: Better Cities Full or Better Cities IC components.`
- [x] `road+bridges.esp has been detected. New Roads & Bridges Revised and all dependent patches must be uninstalled before using Roads of Cyrodiil. See Roads of Cyrodiil readme for upgrade instructions.`
- [x] `Make sure to rename your main Storms & Sounds plugin (OBSE-Storms & Sound.esp, EW-Storms & Sound.esp, etc.) to "Storms & Sound.esp".`
- [x] `Use .ini tweak or Wrye Bash Bashed Patch tweak instead where possible to avoid conflicts.`
- [ ] `Realistic hunger mods and vampire mods may conflict seriously.`
- [x] `Only use if using the separate Better Cities .esps`
- [x] `Obsolete. Remove this and update Better Cities to latest version.`
- [x] `Only activate one Life Detected esp at a time.`

**Comment by Ortham** [comment]
`If not using Wrye Bash load this later (though then it will override some things).`: I've removed these messages entirely, because they're not at all helpful.

`Use Standalone MOBS if using Frans or OMOBS if using FCOM/OOO. Both versions can be found [here](http://www.nexusmods.com/oblivion/mods/28537)`: These messages were attached to the UOP and USIP for some reason, I removed them because it's unclear what they've got to do with the unofficial patches.

`Probably not compatible with OOO. Untested.`: Again, this is unhelpful, so I removed them.

`Make sure to install the additional mods (listed in the readme).`: We could stick RTFM messages to every plugin with dependencies, but we don't. Removed.

`Realistic hunger mods and vampire mods may conflict seriously.`: Removed because it's not helpful to the user. Everything may conflict seriously with everything, it's knowing what actually does that counts.
