### ISSUE TITLE
KVatch Rebuilt needs "Relations" tag

### ISSUE THREAD

**Issue by Arthmoor** [loot/oblivion#180]
Kvatch Rebuilt.esp as of version 3.0RC2 needs the "Relations" tag added to its list in LOOT. Without it, people using TIE.esp (which loads before KR) will override the changes KR is making between the player and the city guards.

**Comment by MacSplody** [comment]
> Kvatch Rebuilt.esp as of version 3.0RC2 needs the "Relations" tag added to its list in LOOT. Without it, people using TIE.esp (which loads before KR) will override the changes KR is making between the player and the city guards.

Might need a `Factions` tag as well.

![image](https://user-images.githubusercontent.com/1944639/81512010-3457ff80-9315-11ea-9bf2-1d3979bce8aa.png)
