### ISSUE TITLE
Open Cities Classic + Unique Landscapes + Lost Spire Cleaned Up scribes 

### ISSUE THREAD

**Issue by arosenow** [loot/oblivion#1831]
Hi, 
The current sort order places 
ULM OpenCitiesClassic-UniqueLandscapes patch.esp
before
OCC + Lost Spires + Cleaned Up Scribe.esp
The latter undoes some fixes to the East gate area and causes the water to be missing

**Comment by sibir-ine** [comment]
Can you please provide links to where you downloaded those plugins?

**Comment by arosenow** [comment]
Please find the links to the installed mods below: 
https://www.afkmods.com/index.php?/files/file/253-open-cities-classic/
https://www.afkmods.com/index.php?/files/file/2371-open-cities-patch-collection-for-oblivion/
https://www.nexusmods.com/oblivion/mods/12997
https://www.nexusmods.com/oblivion/mods/50146
https://www.nexusmods.com/oblivion/mods/19370

**Comment by arosenow** [comment]
The cells that are impacted are just outside cheydinhal east gate which is an error that can be observed if you played with Open Cities Classic + Unique landscapes without a patch

**Comment by MacSplody** [comment]
I'm not seeing any conflict in xEdit between `ULM OpenCitiesClassic-UniqueLandscapes patch.esp` and `OCC + Lost Spires + Cleaned Up Scribe.esp`.

![image](https://github.com/loot/oblivion/assets/1944639/bedb0881-54f8-4854-9c8f-0538c57caf38)

**Comment by arosenow** [comment]
Odd, maybe one has an unclean edits because depending on the order I load
them (cleaned up scribe second) it reverts to the pre patch behaviour for
open cities + unique landscapes

**Comment by MacSplody** [comment]
> Odd, maybe one has an unclean edits because depending on the order I load them (cleaned up scribe second) it reverts to the pre patch behaviour for open cities + unique landscapes

Would you mind posting your load order?

**Comment by arosenow** [comment]
I run loot and then I swap those 2 mods that appear to be conflicting each
time and it fixes the issues with OCC+UL

0  0     Oblivion.esm
  1  1     Jog_X_Mod.esm
  2  2     Cobl Main.esm
  3  3     Open Cities Resources.esm
  4  4     Hemingweys Capes Improved.esm
  5  5     NNWAEMaster.esm
  6  6     CM Partners.esm
  7  7     Knights - Revelation.esm
  8  8     Cobl Glue.esp
  9  9     Unofficial Oblivion Patch.esp
 10  a     UOP Vampire Aging & Face Fix.esp
 11  b     Oblivion Citadel Door Fix.esp
 12  c     DLCShiveringIsles.esp
 13  d     Unofficial Shivering Isles Patch.esp
 14  e     Cobl Si.esp
 15  f     DLCHorseArmor.esp
 16 10     DLCHorseArmor - Unofficial Patch.esp
 17 11     DLCOrrery.esp
 18 12     DLCOrrery - Unofficial Patch.esp
 19 13     DLCVileLair.esp
 20 14     DLCVileLair - Unofficial Patch.esp
 21 15     DLCMehrunesRazor.esp
 22 16     DLCMehrunesRazor - Unofficial Patch.esp
 23 17     DLCSpellTomes.esp
 24 18     DLCSpellTomes - Unofficial Patch.esp
 25 19     DLCThievesDen.esp
 26 1a     DLCThievesDen - Unofficial Patch.esp
 27 1b     DLCThievesDen - Unofficial Patch - SSSB.esp
 28 1c     DLCBattlehornCastle.esp
 29 1d     DLCBattlehornCastle - Unofficial Patch.esp
 30 1e     DLCFrostcrag.esp
 31 1f     DLCFrostcrag - Unofficial Patch.esp
 32 20     OCOD+FrostcragSpire Patch.esp
 33 21     Knights.esp
 34 22     Knights - Unofficial Patch.esp
 35 23     OCC-KOTN-Patch.esp
 36 24     Underwater Blur.esp
 37 25     Torch Hotkey.esp
 38 26     Climb.esp
 39 27     Duke Patricks - Friendship Ring For Companion Detection.esp
 40 28     OblivionReloaded.esp
 41 29     Spell Delete.esp
 42 2a     Streamline 3.1.esp
 43 2b     Dynamic Map.esp
 44 2c     Tamriel.esp
 45 2d     Better Dungeons.esp
 46 2e     ElsweyrAnequina.esp
 47 2f     TWMP_Valenwood_Elsweyr.esp
 48 30     ElsweyrPelletine.esp
 49 31     better lights.esp
 50 32     Oblivion Scaling Unclusterfucked.esp
 51 33     Tales from Elsweyr Anequina.esp
 52 34     Sounds of Cyrodiil.esp
 53 35     Balanced NPC Level Cap.esp
 54 36     Hemingweys Capes Improved.esp
 55 37     Oblivion_Character_Overhaul.esp
 56 38     HeartOftheDead.esp
 57 39     LG's Unscaled Enemies.esp
 58 3a     The Lost Spires.esp
 59 3b     New Senchal.esp
 60 3c     Elsweyr Mysteries.esp
 61 3d     Knights - Revelation.esp
 62 3e     BHC_Expanded.esp
 63 3f     Mages Guild Quests.esp
 64 40     MannimarcoRevisited.esp
 65 41     The Lost Spires - Cleaned Up Scribe.esp
 66 42     C&C - The Blackwood Company.esp
 67 43     Cliff_PersonalGuildStorageChest.esp
 68 44     VaultsofCyrodiil.esp
 69 45     Fighters Guild Quests.esp
 70 46     mythsandlegends.esp
 71 47     300_White Stallion 4.esp
 72 48     TOTF.esp
 73 49     Secrets Of Angalayond Cey.esp
 74 4a     NNWAEDungeons-Series2EV.esp
 75 4b     ReneersContainerMod.esp
 76 4c     TOTF Delayer.esp
 77 4d     Better Torches.esp
 78 4e     PersuasionOverhaul.esp
 79 4f     Unique Loot Deleveled.esp
 80 50     MigLockpicking.esp
 81 51     BountyReductionOverTime_standard.esp
 82 52     kuerteeCrimeHasWitnesses.esp
 83 53     Realistic Arrow Flight.esp
 84 54     Duke Patricks - Actors Can Miss Now.esp
 85 55     AdvancedWeaponSkillLeveling.esp
 86 56     Smarter Mercantile Leveling - Multi.esp
 87 57     TimeEnough.esp
 88 58     No Beginning Travel.esp
 89 59     CM Partners.esp
 90 5a     RTT.esp
 91 5b     Tales of Cyrodiil.esp
 92 5c     NNWAREAyleidDungeons_Series1EV.esp
 93 5d     OCC-TOTF-Patch.esp
 94 5e     OCC-RTTv3 Patch.esp
 95 5f     ElsweyrC&CBlackwoodPatch.esp
 96 60     NNWARE06-RhyeliaEmeroEV.esp
 97 61     Jail Break Escape Routes.esp
 98 62     No Anachronistic MQ Comments.esp
 99 63     Rebalanced and Unleveled QGR.esp
100 64     Immersive Character and Dialogue Expansion.esp
101 65     Snowdale - Fighters Guild Quests Patch.esp
102 66     ImprovedSigns.esp
103 67     Extended Dialogue.esp
104 68     Enhanced Grabbing.esp
105 69     Duke Patricks - Fresh Kills Now Alert The NPCs.esp
106 6a     KW-AlliesPlayNicer.esp
107 6b     Syc_LongerDaysShorterNights.esp
108 6c     LightSpellWhiteDimmer.esp
109 6d     NoStealFromYourFactions.esp
110 6e     Faster Arrows and Spells.esp
111 6f     LongerUnconscious.esp
112 70     No Backwards Running.esp
113 71     Balanced Creatures - DLC.esp
           OCO_Eyes_Fix.esp
114 72     Balanced Unleveled Rewards - Complete.esp
115 73     Weapon Improvement Project.esp
116 74     Balanced Creatures.esp
117 75     Friendlier Summons.esp
118 76     Loading Area Begone.esp
119 77     Balanced NPC Level Cap - DLC Patches.esp
120 78     lSkillBasedHarvestChance.esp
121 79     OSU UOP Patch.esp
122 7a     Mannimarco Revisited Rebalance.esp
123 7b     Safe Archmage Storage-2135.esp
124 7c     MannimarcoRevisited UOP Patch.esp
125 7d     DelayThoseDLCs.esp
126 7e     Quest NPCs Run.esp
127 7f     SupremeMagickaLite.esp
128 80     Near Miss Alerts.esp
129 81     Ronyns Realistic and Fun Acrobatics-8494.esp
130 82     dizzySafeSave.esp
131 83     P1DkeyChain.esp
132 84     Finger of the Mountain Fix-3152.esp
133 85     HOD_delayer.esp
134 86     DD_ProximitySneakPenalty.esp
135 87     SB_WeaponDropFix.esp
136 88     Better Dungeons - Balance Patch.esp
           LIPTemplate.esp
           OCO DLC Faces.esp
137 89     GalerionUnarmoredAcrobatics.esp
138 8a     JumpModifier.esp
139 8b     aATRLeveling.esp
140 8c     stickierenemytargeting.esp
141 8d     aATRRetroStats.esp
142 8e     Unique Landscapes.esp
143 8f     Rathunas01.esp
144 90     ULM HeartoftheDead-ArriusCreek patch.esp
145 91     ULE MythsAndLegends2-EasternPeaks patch.esp
146 92     ULM TalesFromElsweyr-BravilBarrowfields patch.esp
147 93     ULE TearsOfTheFiend-CheydinhalFalls patch.esp
148 94     ULE Anequina-FallenleafEverglade patch.esp
149 95     ULE AyleidRuinsExpanded-JerallGlacier patch.esp
150 96     ULE UnofficialOblivionPatch-CorboloRiver patch.esp
151 97     Open Cities New Sheoth.esp
152 98     Open Cities Outer Districts.esp
153 99     Open Cities Classic.esp
154 9a     OCC + Lost Spires + Cleaned Up Scribe.esp
155 9b     ULM OpenCitiesClassic-UniqueLandscapes patch.esp
           Cobl Filter Late MERGE ONLY.esp
156 9c     Bashed Patch, 0.esp
157 9d     kuerteeCleanUp.esp

**Comment by MacSplody** [comment]
`ULM OpenCitiesClassic-UniqueLandscapes patch.esp` does need `C.Regions` and `C.Water` tags.

![image](https://github.com/loot/oblivion/assets/1944639/0ba42deb-99d7-4a9d-899a-6080e3a18e3a)

Water height change won't show up as a conflict.
![image](https://github.com/loot/oblivion/assets/1944639/aac00df6-9f9f-4b93-a78c-e01a6c14dc54)

---

You can test by adding `C.Regions` and `C.Water` tags to `ULM OpenCitiesClassic-UniqueLandscapes patch.esp`.
And then place `ULM OpenCitiesClassic-UniqueLandscapes patch.esp` before `OCC + Lost Spires + Cleaned Up Scribe.esp`.

**Comment by MacSplody** [comment]
Change carried forward when tag is added, that was probably the issue.
UL and OCC both have `C.Water` tags, so OCC reverts the change, which means we need to tag the patch.

![image](https://github.com/loot/oblivion/assets/1944639/04498697-2913-4d40-ae19-3a00f2e8fd45)

Edit:
Better screenshot

![image](https://github.com/loot/oblivion/assets/1944639/8af72d3c-75d1-4512-8be6-91413cf0cc8a)

**Comment by arosenow** [comment]
I added those tags and reran loot, if i don't change the order of those 2 plugins this is what i see.

[image: image.png]

**Comment by MacSplody** [comment]
> I added those tags and reran loot, if i don't change the order of those 2 plugins this is what i see. [image: image.png]

Did you remake the bashed patch?

**Comment by arosenow** [comment]
Cheers! I'll try again

**Comment by arosenow** [comment]
I regenerated the bash patch, it doesn't appear to be resolving the missing
river, I put those tags on the OCC + ULM patch C.Water, C.Region

**Comment by MacSplody** [comment]
So like this?

![image](https://github.com/loot/oblivion/assets/1944639/f2e7855b-a025-4966-8a32-6d83d513f5a5)

**Comment by arosenow** [comment]
[image: image.png]

**Comment by arosenow** [comment]
[image: image.png]

**Comment by MacSplody** [comment]
> [image: image.png]

I can't view those images.

**Comment by arosenow** [comment]
They were pictures from bash confirming those tags coming from a user list
as I added them in loot

**Comment by MacSplody** [comment]
> Please find the links to the installed mods below: https://www.afkmods.com/index.php?/files/file/253-open-cities-classic/ https://www.afkmods.com/index.php?/files/file/2371-open-cities-patch-collection-for-oblivion/ https://www.nexusmods.com/oblivion/mods/12997 https://www.nexusmods.com/oblivion/mods/50146 https://www.nexusmods.com/oblivion/mods/19370

[Direct download](https://web.archive.org/web/20170925102834/http://www.lostspires.com/misc/thelostspiresv14.zip) for The lost Spires - Site for mod is down.
