### ISSUE TITLE
Oblivion Content Restoration Project Bash Tags

### ISSUE THREAD

**Issue by Sabre142** [loot/oblivion#187]
I might suggest these bash tags for Oblivion Content Restoration Project (https://www.nexusmods.com/oblivion/mods/45909). It currently has no tags in the ESP description and is not in the masterlist.

{{BASH:Actors.ACBS,Actors.AIData,Actors.AIPackages,Actors.CombatStyle,Actors.Spells,Actors.Stats,Factions,Graphics,Invent.Add,Invent.Remove,Names,NPC.Class,NPC.Race,Scripts,SpellStats,Stats}}

**Comment by MacSplody** [comment]
> {{BASH:Actors.ACBS,Actors.AIData,Actors.AIPackages,Actors.CombatStyle,Actors.Spells,Actors.Stats,Factions,Graphics,Invent.Add,Invent.Remove,Names,NPC.Class,NPC.Race,Scripts,SpellStats,Stats}}

All of those are fine, except `SpellStats`. The only changes relevant to that tag are shared with UOP.
I've also added two other tags `Npc.EyesOnly` and `Actors.AIPackagesForceAdd`.
