### ISSUE TITLE
Ultimate Leveling listed as incompatible with AVUncapper.dll

### ISSUE THREAD

**Issue by ewelsh42** [loot/oblivion#1894]
LOOT is currently treating the co-existence of Ultimate Leveling.esp and AVUncapper.dll as an error, flagging them as incompatible.  I'm thinking this is probably stemming from the Ultimate Leveling readme where it states: "Do not use this mod with other character leveling and/or uncapper mods".  However, after using them together myself, and searching for "uncapper" in the Nexus POSTS for Ultimate Leveling, it looks like this is more of a "recommendation" than a true incompatibility.  Repeatedly, and consistently, the Ultimate Leveling author states that, although they are against the use of uncapper mods for balance reasons, and have not tested them or added (much) support for them, they should probably not cause any problems.

A 2021-02-15 post from Maskar summarizes the general state of uncapper compatibility nicely: "Uncapper mods are likely not incompatible. I have however not tested or added specific support for them. Imo all they do is create an unrealistic situation where the player character would have higher skills than npcs, making the game easier than intended. I would recommend lowering the leveling speed instead".

Since then, the author has, in fact, added limited support for uncapper mods in XP leveling mode, where an uncapper mod is actually *required* for that limited support to have any useful effect, as can be found in statements in various other posts.  There are also quite a few posts that skill uncappers should work in Realistic leveling mode (and appears to work just fine when I use the setavskill console command to test it).

Uncapper mods may not work entirely as expected (skills and/or attributes may remain capped, depending on the Ultimate Leveling settings), but they are not actually "incompatible", AV Uncapper does not actually break anything or cause any instability issues in Ultimate Leveling.  Even if levels and/or skills may remain capped by Ultimate Leveling overriding the uncapper behavior, uncapper mods will still work fine for removing limitations on base damage within (and above) the 100 attribute/skill limits, such as the 15 damage limit on Hand-to-Hand damage, and for extending support for effects of temporary (fortify) buffs above 100.

The documentation to not use uncapper mods appears to be more from the author being against their use for balance reasons, rather than any actual incompatibility.  I would like to suggest changing the incompatibility error in the master list metadata into a warning/note to inform the user that levels/skills may remain capped depending on Ultimate Leveling ini settings, but that it isn't an actual incompatibility.

**Comment by sibir-ine** [comment]
Thanks for the report, done.
