### ISSUE TITLE
Fix broken links

### ISSUE THREAD

**Issue by WrinklyNinja** [loot/oblivion#19]
pStyl3 reported a few broken links, a couple of which I haven't yet fixed:

```
http://tesrenewal.com/forums/morroblivion/mods/753
http://tesrenewal.com/forums/oblivion/morroblivion-mod-releases/3294
http://www.nexusmods.com/oblivion/mods/43299
```

**Comment by Freso** [comment]
The two tesrenewal.com URLs seem fine? The Nexus Mods one seems to have been hidden by the mod author, not completely removed/deleted from Nexus. Should it still be removed from the masterlist? I would probably vote to keep it there, at least until/unless another URL pops up as the official one for those mods.

**Comment by pStyl3** [comment]
The first two links seem to be working again. Maybe the server was simply not working when I checked it? Probably.

The mod on Nexus seems to be "Glowing Respawning Varla and Welkynd Stones" by Khettienna:
http://www.nexusmods.com/oblivion/users/732048/?

Judging by the comment on this mod description, that is:
http://www.nexusmods.com/oblivion/mods/43484/?

Khettienna could be asked what his/her intentions are with the mod. That said, the mod has been hidden for at least a solid month now.

**Comment by Freso** [comment]
But as long as it is hidden, it could potentially be "reborn" again at the same URL, and people using LOOT's data to get to the mod page will see that "the mod author has chosen to hide it" or however the text goes, instead of getting a straight up 404, so in my eyes the link is not currently dead per se.

**Comment by WrinklyNinja** [comment]
Yeah, I'd say keep the hidden file link until Khettienna decides one way or another, because it's not actually incorrect. A month isn't that long, after all.

**Comment by Freso** [comment]
Alright then. Let's close this and open new issues for actual dead links. :)

**Comment by Khettienna** [comment]
Hiya!  I just came across this.  Not sure if it's still relevant for you guys, but the "glowing" version of Respawning Varla & Welkynd stones was posted by The Vyper based on my original (with my blessing).  He's the one you should contact in regards to it.  If anyone gets hold of him and gets permission, I still have a copy of his version (as it's actually the one I use) and I can re-upload it to Nexus & TESA.

Edit:  The TESA upload is still active!  http://tesalliance.org/forums/index.php?/files/file/1465-glowing-respawning-varla-welkynd-stones/
