### ISSUE TITLE
Failed to sort: Cyclic interaction

### ISSUE THREAD

**Issue by PimTournaye** [loot/oblivion#218]
[LOOTDebugLog.txt](https://github.com/loot/oblivion/files/5147109/LOOTDebugLog.txt)

Getting this error, any idea what I should do?

> 
> Cyclic interaction detected between "bgIntegrationEV.esp" and "xulTheEasternPeaks.esp":
> 
> bgIntegrationEV.esp
>  [Master]
> ULM IntegrationTheStrandedLight-EasternPeaks patch.esp
>  [Group]
> xulSkingradOutskirts.esp
>  [Master]
> ROC+RST+Skingrad Outskirts.esp
>  [Group]
> xulTheEasternPeaks.esp
>  [Masterlist Load After]
> bgIntegrationEV.esp

**Comment by PimTournaye** [comment]
Failed to sort plugins. Details:
Cyclic interaction detected between "bgIntegrationEV.esp" and "xulTheEasternPeaks.esp":

bgIntegrationEV.esp
 [Masterlist Requirement]
ULE IntegrationTheStrandedLight-SilverfishRiverValley patch.esp
 [Group]
xulSkingradOutskirts.esp
 [Master]
ROC+RST+Skingrad Outskirts.esp
 [Group]
xulTheEasternPeaks.esp
 [Masterlist Load After]
bgIntegrationEV.esp

Also no Userlist.yaml to be found.

**Comment by MacSplody** [comment]
Issue resolved on discord.
https://discord.com/channels/473542112974077963/473542230095822848/749679551864373358
![image](https://user-images.githubusercontent.com/1944639/91671830-e2d0bc00-eb21-11ea-9eb8-abefaa9d4f32.png)
