### ISSUE TITLE
Tona's_ModsStore.esp still marked as dirty after cleaning with TES4Edit

### ISSUE THREAD

**Issue by genderneutralnoun** [loot/oblivion#219]
[Tonas Mods Store](https://www.nexusmods.com/oblivion/mods/29090)
(I'm not a coder and am unfamiliar with the proper format for submitting issues on GitHub. Please correct me if I've done anything wrong.)
I use Wrye Bash as my mod manager for Oblivion. It marked Tona's_ModsStore.esp as dirty, so I cleaned it in TES4Edit with QuickAutoClean. Upon refreshing my plugin list, Wrye Bash had still marked it as dirty, so I tried cleaning it again, but the report said that there were no changes. Knowing that Wrye Bash uses LOOT's dirty mod list, I opened LOOT and sorted my plugin list. LOOT still marked the plugin as dirty. I uninstalled and re-installed LOOT, ran it again, and it was still marked as dirty. I checked the mod for dirty edits with Wrye Bash, so I'm confident the mod is actually clean, but seeing the mod be marked dirty is annoying, and I thought it would be proper to report this somewhere.

**Comment by MacSplody** [comment]
@genderneutralnoun Yeah, the file is clean, you can ignore it until it's updated.
That cleaning info was carried over from the BOSS masterlist.
So it has been wrong for a long time.

```yaml
  - name: 'Tona's_ModsStore.esp'
    clean:
      - crc: 0x8DD1E120
        util: 'TES4Edit v4.0.3'
```

**Comment by MacSplody** [comment]
@genderneutralnoun Fixed, update your masterlist.
