### ISSUE TITLE
Error reported for Hud Status Bars may be incorrect (tiny detail)

### ISSUE THREAD

**Issue by gkhoman** [loot/oblivion#22]
For Hud Status Bars.esp Loot says "This plugin requires "../obse_loader.exe" to be installed but it is missing".

I am running the steam version of ESIV, so have obse_steam_loader.exe, and not obse_loader.exe installed and HSB appears to be working as expected: e.g. I get the extra encumbrance status bar HSB installs by default, and modifications I make to HSB's ini file show up in game.

**Comment by Ortham** [comment]
Yeah, the OBSE check should look for its DLL, which is used on both Steam and non-Steam installs.
