### ISSUE TITLE
TES4: Incorrect "Better Imperial City.esp" vs "Sounds of Cyrodiil.esp" order

### ISSUE THREAD

**Issue by d1zzy** [loot/oblivion#23]
Hi,

While putting together this doc:
https://medium.com/the-backlog-gog-com-stream-team-blog/an-oblivion-modding-guide-9274b2640231

I ran into the following issue: LOOT puts [Sounds of Cyrodiil.esp](http://www.nexusmods.com/oblivion/mods/39804/) after [Better Impercial City.esp](http://www.nexusmods.com/oblivion/mods/16513/) which results in issues. For example in the Arena district, where the entrance to the arena is, the floor is raised relative to the arena effectively making it impossible to enter the Arena. Once I manually moved Better Imperial City.esp to follow Sounds of Cyrodiil.esp this issue was fixed. I noticed similar pieces of raised floor (looks like ground/dirt, where normally in the IC the floor should look like cobblestone) in other IC areas with the incorrect ESP order. Note that BOSS seems to order things fine (it creates a drastically different ESP order where all the Better Cities ESPs are clustered around at the end of the mod list, just before Bashed Patch.esp).

Thanks!

**Comment by Ortham** [comment]
Thanks.
