### ISSUE TITLE
Change license to Creative Commons Zero

### ISSUE THREAD

**Issue by Freso** [loot/oblivion#24]
I would like to relicense the LOOT masterlists/repositories to be under the [Creative Commons Zero license](https://creativecommons.org/publicdomain/zero/1.0/) (effectively submit them to the public domain). See https://github.com/loot/loot.github.io/issues/61 for more thoughts on this.

@WrinklyNinja, @Sharlikran, @egocarib, @William-Imm, @SilentSpike, @garthand, @shadowslasher410, @Felerius, @Sctumsempra (these are [all the contributors listed on GitHub](https://github.com/loot/oblivion/graphs/contributors)) if you agree with moving to this much more free license, please write a comment here confirming this.

<details>
<summary>Agreed LOOT contributors</summary>

- [x] @WrinklyNinja
- [x] @Sharlikran 
- [x] @Freso
- [x] @egocarib
- [x] @William-Imm
- [x] @SilentSpike a.k.a. kymckay
- [x] @garthand
- [x] @Felerius
- [x] @CptMcSplody
- [x] @shadowslasher410
- [x] @sibir-ine
- [x] @Infernio 
- [x] @DaCoolX 
- [x] @ddbb07 
- [x] @Sabre142 
</details>

<details>
<summary>Agreed BOSS contributors not already mentioned</summary>

- [x] @Arthmoor
- [x] @mhahn123
- [x] @TokcDK
- [x] @valda
- [x] @Foffy123
- [x] @leandor
- [x] @RandomNadir007
- [x] @deathssoul
- [x] @Vacuity729
- [x] @spaceoden
- [x] @KadVenku
- [x] @NickDickinsonWilde
- [x] RiddlingLynx `<riddlinglynx at gmail.com>` a.k.a. @Valtarien
</details>

Remaining LOOT contributors:
- [x] ~~@Sctumsempra~~ Clean-room reimplemented contributions

Remaining BOSS contributors:
- [x] ~~ZiggyX200 `<ziggyx200 at gmail.com>`~~ Clean-room reimplemented contributions
- [x] ~~gabrielmonn `<gabrielmonn at gmail.com>`~~ Clean-room reimplemented contributions

Once/if everyone accepts, I'll change the license.

**Comment by Freso** [comment]
@WrinklyNinja If you're able to get a list of BOSS contributors prior to the conversion that haven't been mentioned above, that'd be great. :)

**Comment by Ortham** [comment]
The BOSS contributors not mentioned above are:

- @NickWilde1990
- @Arthmoor
- @mhahn123
- @TokcDK
- @valda
- @Foffy123
- @leandor
- @RandomNadir007

Also the following that I haven't been able to match to GitHub accounts, who may all be from the Google Code days:

```
menduki <menduki@yandex.ru>
jpearce <jpearce@pacific.net.au>
ZiggyX200 <ziggyx200@gmail.com>
gabrielmonn <gabrielmonn@gmail.com>
Vacuity <burntfield@gmail.com>
RiddlingLynx <riddlinglynx@gmail.com>
deaths_soul (MCP) <NULL>
KadVenku <venkukad@gmail.com>
Space Oden69 <jacksonleist@gmail.com>
AliTheLord <alistair.rainbowdukane@gmail.com>
KadVenku <venkukad@gmx.de>
```

**Comment by Arthmoor** [comment]
No problem with this.

**Comment by Ortham** [comment]
I agree.

**Comment by kymckay** [comment]
I agree.

**Comment by Sharlikran** [comment]
+1

**Comment by valda** [comment]
I agree.

**Comment by deathssoul** [comment]
The LOOT masterlists do not need any input from me, I just work with the core BOSS code so you can probably take me off the list above.

**Comment by Freso** [comment]
@deathssoul But you made edits to the BOSS masterlists prior to their conversation to the new LOOT format, which means you may potentially have partial copyright of the current LOOT masterlists. So just in case you do, it'd be great if you could approve of the license change (if you agree with it, that is :) ) – preferably with a comment on each of the issues. :)

**Comment by deathssoul** [comment]
Only edits I made were for the program version number but, since you insist, CC0 is fine by me here. I like GPL3+ for code but haven't really formed an opinion on metadata yet. :)

**Comment by egocarib** [comment]
I support this.

**Comment by Freso** [comment]
@KadVenku gave permission here: https://github.com/loot/loot.github.io/issues/61#issuecomment-410265328
@Vacuity729 gave permission here: https://github.com/loot/loot.github.io/issues/61#issuecomment-410320606
@spaceoden gave permission here: https://github.com/loot/loot.github.io/issues/61#issuecomment-410348382

**Comment by Felerius** [comment]
I agree.

**Comment by MacSplody** [comment]
I agree.

**Comment by mhahn123** [comment]
I don't have any issues with this

**Comment by WilliamImm** [comment]
No issues here (formerly "William-Imm")

**Comment by Foffy123** [comment]
Agreed.

**Comment by leandor** [comment]
Answering through mail (@leandor here), since I cba to re-login to GitHub
(been ages since I logged in to the site and I'd probably need to recover
password and fiddle with the 2FA external code generator :P)

I think I never contributed stuff to any masterlist myself, but just in
case, you have my Agreed!

**Comment by pStyl3** [comment]
@garthand 
@shadowslasher410 
@Sctumsempra 
@NickWilde1990 @NickDickinsonWilde
@TokcDK
@RandomNadir007

Sorry to ping you again, but if time permits, could you evaluate the above mentioned situation?
Thank you.

**Comment by TokcDK** [comment]
Agree. 
..Only noticed reply where asked me to comment also here.

**Comment by pStyl3** [comment]
@garthand agreed here: https://github.com/loot/skyrim/issues/196#issuecomment-515155244

**Comment by RandomNadir007** [comment]
Sorry this has been hanging around for so long. I think I replied to a Nexus message a few years ago saying "go ahead". 

Go ahead! I've no problem with the license being changed to public domain.

**Comment by sibir-ine** [comment]
Infernio agreed in https://github.com/loot/skyrim/issues/196#issuecomment-817335752 (posting to keep track).

**Comment by sibir-ine** [comment]
@shadowslasher410 agreed in https://github.com/loot/skyrim/issues/196#issuecomment-817338963.

**Comment by sibir-ine** [comment]
DaCoolX agreed in https://github.com/loot/skyrim/issues/196#issuecomment-817339754.

**Comment by sibir-ine** [comment]
@Sctumsempra @NickDickinsonWilde

If you guys are still around, could you please read this issue & state whether you agree?

**Comment by Ortham** [comment]
Here are links to view the outstanding BOSS contributors' contributions (in the BOSS masterlist):

- ~~[NickDickinsonWilde](https://github.com/boss-developers/oblivion/commits/master?author=NickDickinsonWilde): lots of pages of commits~~ Agreed
- ~~[gabrielmonn](https://github.com/boss-developers/oblivion/commits/master?author=gabrielmonn@gmail.com): 1 page of commits ([TODO](https://gist.github.com/Infernio/d1c02e4436cb1c96d5a85f33bf3891a9))~~ Clean-room reimplemented contributions, agreement not required
- ~~[RiddlingLynx](https://github.com/boss-developers/oblivion/commits/master?author=riddlinglynx@gmail.com): 1 page of commits~~ Agreed
- ~~[ZiggyX200](https://github.com/boss-developers/oblivion/commits/master?author=ziggyx200@gmail.com): 1 page of commits~~ Clean-room reimplemented contributions, agreement not required
- ~~[AliTheLord](https://github.com/boss-developers/oblivion/commits/master?author=alistair.rainbowdukane@gmail.com): 1 commit~~ Changes no longer present, agreement not required

**Comment by Infernio** [comment]
[AliTheLord's changes](https://github.com/boss-developers/oblivion/commit/7a6a2f0ccfcea9863b902f7f76ab3557e9b14a17) are still present: https://github.com/loot/oblivion/blob/035caf9704fed609de7248fa9b4c2b6da5683e61/masterlist.yaml#L13375-L13376

**Comment by sibir-ine** [comment]
Thanks @Infernio! That message will likely get refactored as part of #317, however, I can't find any mention of the dummy plugin on [The Ayleid Steps](https://www.nexusmods.com/oblivion/mods/16316/), [Frostcrag Reborn De-Isolated](https://www.nexusmods.com/oblivion/mods/40752/), or the original [Frostcrag Reborn](https://www.nexusmods.com/oblivion/mods/9769/), so I think we can remove it entirely.

**Comment by sibir-ine** [comment]
@NickDickinsonWilde is definitely still around, he's pretty active on twitter. I sent him a DM & email just in case, but, if he doesn't respond, he is a former Wyre Bash maintainer (Pacific Morrowind). Maybe @lojack5 or @Utumno can get in contact with him.

**Comment by Infernio** [comment]
There is one mention of a dummy ESP for Frostcrag Reborn in [this post](https://forums.nexusmods.com/index.php?/topic/53964-ayleid-steps-1-0/page-16#entry1645715), but that was back in 2010. The readme in the most recent download doesn't include any mention of such a dummy ESP anymore, so this is probably indeed outdated.

**Comment by ddbb07** [comment]
I agree/ im okay with this

**Comment by Sabre142** [comment]
I 100% agree and am OK with moving to the new license. For any and all masterlists I contributed to.

**Comment by sibir-ine** [comment]
NickDickinsonWilde agreed in https://github.com/loot/loot.github.io/issues/61#issuecomment-817452568.

**Comment by sibir-ine** [comment]
Sctumsempra has one [change](https://github.com/loot/oblivion/commit/cf0916784e1455842887740a1b3c09de6d351442) still present:


https://github.com/loot/oblivion/blob/04e76f0d0c0d842f463e812d825790af3a2990be/masterlist.yaml#L2170
https://github.com/loot/oblivion/blob/04e76f0d0c0d842f463e812d825790af3a2990be/masterlist.yaml#L2176

Both mods are still around (NSFW warning), but the change may be insignificant enough to be removed.

I investigated, & they conflict in a few `RACE` records. While OCO loading after does resolve more conflicts, they still both lose no matter which way they're sorted. I can't find a compatibility patch between the two, so removing the rule outright isn't ideal. Maybe we could replace it with an incompatibility message, but that seems excessive.

**Comment by sibir-ine** [comment]
nateious only [removed](https://github.com/loot/oblivion/commit/201c043e1dd2f841f5eafa18b0444f277ac923ce) a few lines, so we don't need their agreement.

**Comment by ddbb07** [comment]
RiddlingLynx created [this mod](https://www.nexusmods.com/oblivion/mods/14901/) on the nexus and his current name is Valtarien, he was last active in July 2018 on this account, this might also be his current [GitHub page](https://github.com/Valtarien/) the GitHub page was last active January 2021.

**Comment by Infernio** [comment]
I'm going over ZiggyX200's contributions, most of them are tag additions which can be 'clean-roomed' by downloading the plugins and adding necessary tags without considering the tags that were previously present.

Edit: TODO list with everything they contributed that needs replacing: https://gist.github.com/Infernio/6ce44c95e23a44c2508d283d1bfcdb41

**Comment by ddbb07** [comment]
I've messaged RiddlingLynx on the Nexus directing him to this issue

**Comment by sibir-ine** [comment]
> I've messaged RiddlingLynx on the Nexus directing him to this issue

@ddbb07 Thanks!

**Comment by nateious** [comment]
> nateious only removed a few lines, so we don't need their agreement.

I agree anyway :)

**Comment by sibir-ine** [comment]
> I agree anyway :)

Thanks for responding! Better to have your agreement than not.

**Comment by Valtarien** [comment]
Sorry for being late to the party. You have me listed as "RiddlingLynx <riddlinglynx at gmail.com> On Nexus," so I emailed you from that GMail account. I very much am in support of the open source community, so I highly support this move. To be explicit: I agree to the change for all masterlists.

Please note that I no longer go by RiddlingLynx, or use that email address regularly, but instead "Valtarien," (valtarien@tutanota.com). My Nexus account listing should confirm this, as well as my GitHub account. I will need to update my information in the LOOT contributor list, apparently. I have not been active lately, but do get involved as time allows, so I would like to remain on the roster.

Thanks,
Anthony (Valtarien, formerly RiddlingLynx)

**Comment by Valtarien** [comment]
Sorry for being late to the party. You have me listed as "RiddlingLynx <riddlinglynx at gmail.com> On Nexus," so I emailed you from that GMail account. I very much am in support of the open source community, so I highly support this move. To be explicit: I agree to the change for all masterlists.

Please note that I no longer go by RiddlingLynx, or use that email address regularly, but instead "Valtarien." My Nexus account listing should confirm this, as well as my GitHub account. I will need to update my information in the LOOT contributor list, apparently. I have not been active lately, but do get involved as time allows, so I would like to remain on the roster.

Thanks,
Anthony (Valtarien, formerly RiddlingLynx)

**Comment by Valtarien** [comment]
Sorry for being late to the party. You have me listed as "RiddlingLynx <riddlinglynx at gmail.com> On Nexus," so I emailed you from that GMail account. I very much am in support of the open source community, so I highly support this move. To be explicit: I agree to the change for all masterlists.

Please note that I no longer go by RiddlingLynx, or use that email address regularly, but instead "Valtarien." My Nexus account listing should confirm this, as well as my GitHub account. I will need to update my information in the LOOT contributor list, apparently. I have not been active lately, but do get involved as time allows, so I would like to remain on the roster.

**Comment by sibir-ine** [comment]
~~TODO list with gabrielmonn's contributions that can be clean-room reimplemented.~~

**Comment by Infernio** [comment]
Argh, you were slightly faster :P
Here's [my version](https://gist.github.com/Infernio/d1c02e4436cb1c96d5a85f33bf3891a9). Turns out you can use GitHub's markdown for gists and it will render the checkboxes as well.

**Comment by sibir-ine** [comment]
> 
> 
> Argh, you were slightly faster :P

Lol, my bad! I thought you were busy finishing up the last of Ziggy's contributions. They're almost entirely the same, so I'll just unlist mine & make a comment of the entry I think you missed.
