### ISSUE TITLE
Dirty edits on various mods

### ISSUE THREAD

**Issue by AmperAndSand** [loot/oblivion#32]
Reporting dirty edits on various mods:

https://www.nexusmods.com/oblivion/mods/23296/
Smarter Bandits.esp, 24E8FDC8, DIRTY: 14 ITM, 8 UDR records

https://www.nexusmods.com/oblivion/mods/45249
BMEnchantmentRebalance.esp, 41713073, DIRTY: 22 ITM, 0 UDR records
BalancedMagic.esp, 0D32E9EA, DIRTY: 3 ITM, 0 UDR records

https://www.nexusmods.com/oblivion/mods/44766
Trails Of Cyrodiil Merged Vanilla.esp, CE5C4FF8, DIRTY: 21 ITM, 189 UDR records

https://www.nexusmods.com/oblivion/mods/45977
ReanimationSpellVendor.esp, E25F5AF6, DIRTY: 9 ITM, 0 UDR records

https://www.nexusmods.com/oblivion/mods/14376
Fair x2 Spawns v1.0.esp, 970E0DFE, DIRTY: 14 ITM, 0 UDR records

**Comment by MacSplody** [comment]
@AmperAndSand Thanks, cleaning info has been added for these mods.
FYI Cleaning steps have changed with the latest version of xEdit.

> Due to Improvements made to the cleaning process with the official release of xEdit 4.0.x+, any mods which were verified as clean with older versions of xEdit may now require additional cleaning. A guide for running xEdit 4.0.x+ in **Quick Auto Clean** mode can be found here

https://tes5edit.github.io/docs/5-mod-cleaning-and-error-checking.html#s_5-3-2
