### ISSUE TITLE
LOOT added tags break let there be flowers

### ISSUE THREAD

**Issue by Laulajatar** [loot/oblivion#325]
> ###### Environment, Landscape & Flora ######
  - name: 'lLet there be Flowers.esp'
    url: [ 'https://www.nexusmods.com/oblivion/mods/49616/' ]
    tag:
      - Deactivate
      - Graphics
      - NoMerge

Adding Graphics, NoMerge and Deactivate will break it if used with Enhanced Vegetation.
https://i.imgur.com/2lDzEag.png

This plugin doesn't only need the graphics part, it also needs the density part of the record. On the default esp, this will break only the poppies by setting the density to 15, making them not show up. But several people need the optional "50 density" download of let there be flowers (same esp name) for flowers to show up at all and overwriting them all with 25 again would break the whole mod.

**Comment by MacSplody** [comment]
> Adding Graphics, NoMerge and Deactivate will break it if used with Enhanced Vegetation.
> https://i.imgur.com/2lDzEag.png
> 
> This plugin doesn't only need the graphics part, it also needs the density part of the record. On the default esp, this will break only the poppies by setting the density to 15, making them not show up. But several people need the optional "50 density" download of let there be flowers (same esp name) for flowers to show up at all and overwriting them all with 25 again would break the whole mod.

Hi @Laulajatar ,

Yeah, that makes sense, my testing only included the default version with the below order.

Enhanced Vegetation [100%].esp
lLet there be Flowers.esp

Wrye Bash doesn't have any tag for grass density or wave period so it can't fully patch the two mods at the moment.
It will take the value from whichever plugin is loaded last.

![image](https://user-images.githubusercontent.com/1944639/114322921-b995f680-9b1a-11eb-9654-cf56fe8656ef.png)

![image](https://user-images.githubusercontent.com/1944639/114323337-966c4680-9b1c-11eb-8a30-c693ea94cf55.png)

I'll remove the NoMerge and Deactivate, but BOSS users will need to make sure they place your mod after Enhanced Vegetation.
LOOT sorts the two mods correctly by default.
