### ISSUE TITLE
Kobus Stamina Mod

### ISSUE THREAD

**Issue by Infernio** [loot/oblivion#352]
[Kobus Stamina Mod](https://www.nexusmods.com/oblivion/mods/1862) renames 'fatigue' to 'stamina'. There is a BP tweak that does the same thing (Tweak Names -> Skyrim-style Text: Fatigue -> Stamina), but this mod comes with an XML menu file that renames fatigue in the menus too. Is there a good way to say 'You can use a BP tweak instead, but have to keep this loose file around' via a LOOT msg?

**Comment by sibir-ine** [comment]
I think `*deletePlugin` would work well enough. For reference: `When using **%1%**, it''s recommended that you deactivate or delete this ESP file but keep the resources (e.g. meshes, textures) installed with this mod.`
