### ISSUE TITLE
Italian Retranslation By Forge of Tales and Haexxae wrong load order

### ISSUE THREAD

**Issue by llde** [loot/oblivion#367]
Hi. The mod "ITA - FoT & Hexaae R3.esp" should be sorted immediatly after the end of the ESM files, even before  the Unofficial Oblivion Patch.
It's a retranslation of the game into the Italian language, so if loaded after the UOPs it wil revert the UOP changes (the initial retranslation predate the UOP) .
Current LOOT instead put it after all the DLC + related UP.

(Yes this is a breakage of the common knowledge of "the UOP goes always first" , but it's a sensible exception  )

For now I setted it as a "Very Early Loaders" in Main:Group

**Comment by sibir-ine** [comment]
@llde Can you please provide a link to the mod?

**Comment by llde** [comment]
[ITA - FoT & Hexaae R3.zip](https://github.com/loot/oblivion/files/6407558/ITA.-.FoT.Hexaae.R3.zip)
Nexus down, I uploaded here the esp.

**Comment by sibir-ine** [comment]
@llde As in Nexus is down right now or the mod's page is down? If so, is it available legitimately elsewhere? I ask because we need a legitimate source for the mod for maintenance reasons. If it's been taken down & no one has reuploaded it with proper permissions, it'd be more hassle than it's worth to add it to the masterlist.

**Comment by llde** [comment]
@sibir-ine the mod is uplaoded on the nexus but it's slow like a crawl tonight, and I'm having difficulties to find the page. (It was nexus that was down, but even if now seems available again is still slow)
There should be another place on a forum legitimally, but I don't know if the downlaod is still available. If I recall correclty it was open permisison, derived from a previous version from the now defunct Forge Of Tales group.

**Comment by sibir-ine** [comment]
@llde Ah, I see. There's no rush, so you can just comment when Nexus is faster & you can find it.

**Comment by llde** [comment]
https://www.nexusmods.com/oblivion/mods/41740?tab=description
Found.
The latest official file is in the Update1 update.
It's  pack  that contains also the translated UOP (not last version), but the retranslation is usable standalone (and require no external file)

**Comment by sibir-ine** [comment]
Perfect, thanks!

**Comment by sibir-ine** [comment]
@llde Added, thanks for the report!
