### ISSUE TITLE
Ascension - Immersive Vanilla 'Overhaul'

### ISSUE THREAD

**Issue by sibir-ine** [loot/oblivion#389]
[Link](https://www.nexusmods.com/oblivion/mods/50237/)

- [x] Add Shivering Isles requirement
- [x] Add OBSE v20+ requirement
- [x] Add incompatibilities for similar overhaul mods (e.g., OOO, TIE)
- [x] Add message for [Creature Diversity](https://www.nexusmods.com/oblivion/mods/26634/) patch
- [x] Add message for [Weapons Of Morrowind](https://www.nexusmods.com/oblivion/mods/45440/) patch
- [x] Add Actors.ACBS (various creatures, NPCs)
- [x] Add EffectStats (various magic effects)
- [x] Add EnchantmentStats (various enchantment effects)
- [x] Add Graphics (various record types)
- [x] Add Invent.Add/Change/Remove (deprecated Invent in desc., changes various inventories)
- [x] Add SpellStats (various spells)
- [x] Add Text (various load screens)
- [x] Add do not clean comment as ITMs are intentional

![image](https://user-images.githubusercontent.com/1944639/135736754-82b3e90c-7b6d-4116-9ff2-901e51cd577f.png)

- [x] Add messages that `Combat Groans and Taunts Disabled.esp`, `Level Requires 15 Skill Increases.esp`, `No Starting Map Markers.esp`, & `Ascension - UOP Patch.esp` are included in `Ascension - Push's Tweaks.esp`

- [x] #488

- Recommended to load before [Balanced Creature Stats](https://www.nexusmods.com/oblivion/mods/49194/) & [Balanced NPC Level Cap](https://www.nexusmods.com/oblivion/mods/50094/), LOOT sorts correctly by default

**Comment by MacSplody** [comment]
`No Starting Map Markers.esp` conflicts with `Alternative Beginnings.esp` in MQ01 Tutorial 0001E723.
Default sorting places `No Starting Map Markers.esp` after `Alternative Beginnings.esp`.
Reasonable to assume it also conflicts with other Alt Start modules.
+ also applies to `Ascension - Push's Tweaks.esp`

![image](https://user-images.githubusercontent.com/1944639/135729826-34424bd0-ecf3-4e71-a248-af2263a2fa1c.png)

`Ascension.esp` also modifies MQ01 Tutorial 0001E723, but it's sorted before `Alternative Beginnings.esp`.

![image](https://user-images.githubusercontent.com/1944639/135730345-da97fb87-fdb8-4de2-a2e6-d58ab37f9c76.png)


---

`No Starting Map Markers.esp` conflicts with `Better Imperial City.esp` in placed objects.

![image](https://user-images.githubusercontent.com/1944639/135729908-e0e2bf24-6abe-4da7-8a90-edac81998d2d.png)

Order reversed

![image](https://user-images.githubusercontent.com/1944639/135730276-4fd529bd-f5b2-465f-a289-46df6b89375b.png)

**Comment by MacSplody** [comment]
Also incompatible with [TIE - Tamriel Immersion Experience](https://www.afkmods.com/index.php?/topic/4240-relz-tie-tamriel-immersion-experience/) `TIE.esp`

A lot of overlap between the two mods.

![image](https://user-images.githubusercontent.com/1944639/135737433-8d355594-0725-411c-94c3-ad41c5c20d16.png)

![image](https://user-images.githubusercontent.com/1944639/135737393-5f2f6d4e-3836-4650-9c8d-835c4f765d84.png)
