### ISSUE TITLE
v2 masterlist comment info.

### ISSUE THREAD

**Issue by WrinklyNinja** [loot/oblivion#4]
The following info was recorded from the v2 masterlist silent comments, and non-FCOM-related conditional placements. It needs to get added to the masterlist. Where possible, exact plugin names have been given.
- [x] HrmnsOblivionScriptOptimizationv SI 1.0.esp and similar need to load very early.
- [ ] DLCShiveringIsles.esp should load before the UOP because it's used by the Russian GOTY and would overwrite the UOP otherwise.
- [x] tes4SI-CHS-alpha.esp and tes4-CHS-book.esp need to load before the USIP.
- [x] Natural_Weather_HDR_2.1.3_coloroverride.esp.esp is not a typo.
- [x] Louder Nirnoot.esp is not a typo.
- [x] Ghorak's House.esp must load before Better Benirus Manor.esp
- [x] SOC-RegionalFarms.esp must load before 0WeynonPrioryAlive.esp
- [x] TalosBridgeGateHouse.esp must load before Region Revive - Lake Rumare.esp
- [x] Trade and Commerce.esp must load before Impereal Empire - Unique Castles.esp
- [x] MTCExpandedVillages.esp must load before Region Revive - Lake Rumare.esp
- [x] New Biger Your Personal Dungeon Biger.esp is not a typo.
- [x] Aylied Steps - AN Real Lights patch.esp is not a typo.
- [x] FalkreathGS_RM.esp must load after RumpleModSI.esp.
- [x] CUO_Bravil.esp needs to load before The Lost Spires.esp
- [x] Aundae.esp needs to load before The Lost Spires.esp
- [x] Aundae_OBSE_addon.esp needs to load before The Lost Spires.esp
- [x] The Lost Spires.esp needs to load after Blood&Mud.esp.
- [x] Dollparts' Cherry Brooke Grove.esp needs to load after Dollparts' Cherry Brooke Grove - WAC Patch.esp
- [x] Gold Road Cottage.esp needs to load after Kvatch Rebuilt.esp
- [x] Gold Road Cottage.esp needs to load after Oblivifall - Losing My Religion.esp
- [x] DynamicFootPosition.esp needs to load after personality idles and see you sleep
- [x] Nude Humanlike Spriggan.esp needs to load after Knights - Unofficial Patch.esp
- [x] Nude Humanlike Spriggan Tweaked.esp needs to load after Knights - Unofficial Patch.esp
- [x] Nude Humanlike Spriggan HGEC B.esp needs to load after Knights - Unofficial Patch.esp
- [x] Nude Male Spriggan.esp needs to load after Knights - Unofficial Patch.esp
- [x] training spells.esp should have its warning message conditional on the CRC DD4985A
- [x] SDR Perks And Patches - Nehrim.esp needs to load after Oblivion XP.esp
- [x] SDR_Perks And Patches (Nehrim).esp needs to load after Oblivion XP.esp
- [x] SDR Perks And Patches - Oblivion.esp needs to load after Oblivion XP.esp
- [x] SDR_Perks And Patches (Oblivion).esp needs to load after Oblivion XP.esp
- [x] Birthsigns Expanded.esp needs to load after Cobl Races - Balanced.esp
- [x] Birthsigns Expanded.esp needs to load after Cobl Balanced Races - MMR Patch.esp
- [x] Birthsigns Expanded.esp needs to load after Cobl Races Ren Names Fix.esp
- [x] Better Cities IC Lighting Overhaul.esp needs to load after xulCheydinhalFalls.esp
- [x] Better Clocks-Better Cities IC Light Overhaul.esp needs to load after xulCheydinhalFalls.esp
- [x] Better Clocks for Better Cities 2_0.esp needs to load after xulCheydinhalFalls.esp
- [x] IBOC-Better Citties Patch.esp is not a typo.
- [x] OWC - Players Home.esp needs to load after Better Cities.
- [x] Universitum Arcanorum.esp  needs to load after Better Cities.
- [x] Ahtata Arquamer spike4hair.esp must load after the Bashed Patch.
- Have to go absolutedly last:
  - [x] Ak- Morroblivion Maps HD.esp
  - [x] Hiboriamap.esp
  - [x] MWakeMap.esp
  - [x] MergedMaps.esp
  - [x] Elsweyr Color Map.esp
  - [x] Colored Map for Elsweyr 1.1.esp
  - [x] TamrielWorldspaceCompleteWorldMap.esp
  - [x] TWMP_Tamriel_Ingame_ Map.esp
  - [x] DWIngameMap.esp
- [x] SunderedKeep.esp should load after Better dungeons.esp.
- [x] DMRA BBB Complete Clothing and Armor Replacer.esp should load after Colourwheels Sexy Oblivion OverHaul.esp.
- [ ] Mart's Monster Mod - City Defences.esp should load late (FCOM or not).

**Comment by Ortham** [comment]
I decided not to change any metadata for `DLCShiveringIsles.esp` because the Russian translation was being detected (in BOSS) by proxy, looking for a translation mod. Since that's a pretty rubbish detection mechanism, not to mention modifying DLCShiveringIsles.esp is a bad idea to begin with, I've left it 'broken' in the hopes that a) Russian translations are implemented more sensibly nowadays, or b) if it's still a problem, someone will report it and we can work out a better detection mechanism.

For `Mart's Monster Mod - City Defences.esp`, "load late" is too vague, and the Nexus page's load order guidelines don't mention that, so I added after metadata as suggested on that page.
