### ISSUE TITLE
(Notes) Updates & Testing

### ISSUE THREAD

**Issue by MacSplody** [loot/oblivion#40]
Placeholder.

**Comment by MacSplody** [comment]
`OWC - Players Home.esp`

>       'OWC - Players Home.esp' should load after Better Cities, but nothing
>       more specific is known and the plugin doesn't seem to be available for
>       download and inspection any more, so all main Better Cities plugins are
>       listed below.

Plugin can be found in the `OWC New Dimension - EV Update` under optional files.
[NNWs Mods for OWC ND](https://www.nexusmods.com/oblivion/mods/36260)

Default sorting will place `OWC - Players Home.esp` after `Better Cities`.
Conflicts with Modular version, one persistant record.
'Better Cities BRAVIL.esp' not sure if it's important.

![image](https://user-images.githubusercontent.com/1944639/56017096-2b51c480-5cf6-11e9-8f0a-5f65c1e4fa1a.png)

Conflicts with `OWC - Players Home.esp` after `Better Cities`

![image](https://user-images.githubusercontent.com/1944639/56017662-e890ec00-5cf7-11e9-8964-bf52fde52de6.png)

Conflicts with `OWC - Players Home.esp` after `Open Cities Reborn`

![image](https://user-images.githubusercontent.com/1944639/56018780-f5630f00-5cfa-11e9-93cc-7caf2ce12467.png)

**Comment by pStyl3** [comment]
@CptMcSplody Is this issue intended to be used in the future? Or can it be closed?

**Comment by MacSplody** [comment]
Not at the moment, I can open it again if needed.
