### ISSUE TITLE
Find locations for plugins with anchor `*dirtyPlugin`

### ISSUE THREAD

**Issue by MacSplody** [loot/oblivion#434]
Plugins with anchor `*dirtyPlugin` and without location.

 - [x] `Addendum - Diabloblivion.esp` **No Source**
 - [x] `Ayelid Wells.esp` Original version of [Ayleid Wells Revamped - More Useful Ayleid Well Mod](https://www.nexusmods.com/oblivion/mods/39926) **No Source**
 - [x] `Ayleid Arcane Archer.esp` [Ayleid Arcane Archery](https://www.nexusmods.com/oblivion/mods/39808/)
 - [x] `betterArena.esp` No match for this exact name. Closest match on [Nexus](https://www.nexusmods.com/oblivion/mods/45725) isn't old enough. **No Source**
 - [x] `BNewShockBoltEffects20.esp` [Kals New Shock Lightning Spell Effects](https://www.nexusmods.com/oblivion/mods/10239/)
 - [x] `BNewShockFunnelEffects20.esp` [Kals New Shock Lightning Spell Effects](https://www.nexusmods.com/oblivion/mods/10239/)
 - [x] `Castle Wolfspike2.esp` [Castle Wolfspike V2](https://www.nexusmods.com/oblivion/mods/34320/)
 - [x] `Castle_Almgard-V2.esp` [Castle Almgard](https://www.nexusmods.com/oblivion/mods/14834)
 - [x] `cf_Improved_Barter_Gold.esp` [creepyfellows Improved Barter Gold](https://www.nexusmods.com/oblivion/mods/4367/)
 - [x] `CHILDREN ANNUAD.esp` [CHILDREN'S ANNUAD](https://www.loverslab.com/files/file/9474-childrens-annuad/)
 - [x] `Cliff's Shacks Basements-Radiant AI.esp` [Shack Basements](https://www.nexusmods.com/oblivion/mods/20779/)
 - [x] `Cliff's Shacks Basements.esp` [Shack Basements](https://www.nexusmods.com/oblivion/mods/20779/)
 - [x] `Cliff_CountyNames.esp` [County Names](https://www.nexusmods.com/oblivion/mods/6775/)
 - [x] `CM Emilia.esp` [CM Partners Emilia](https://www.nexusmods.com/oblivion/mods/32760/)
 - [x] `CM Rigel.esp` [CM Partners Rigel](https://www.nexusmods.com/oblivion/mods/27199/)
 - [x] `CM_Kailinda.esp` [CM Companion Kailinda](https://www.nexusmods.com/oblivion/mods/21305/)
 - [x] `Cyrodiil City Guards.esp` **No Source**
 - [x] `DremoraCompanion.esp` [Dremora Companion](https://www.nexusmods.com/oblivion/mods/6977/) 
 - [x] `Enter The Shinobi - Coors916.esp` [Enter the Shinobi](https://www.nexusmods.com/oblivion/mods/8613/)
 - [x] `eyja.esp` [The Romancing of Eyja](https://www.nexusmods.com/oblivion/mods/6960/)
 - [x] `Factions Dark Brotherhood.esp` **No Source**
 - [x] `FearsomeMagicka.esp` [Fearsome Magicka](https://www.nexusmods.com/oblivion/mods/30973/)
 - [x] `First Person Messages.esp` [First Person Messages](https://www.nexusmods.com/oblivion/mods/9606/)
 - [x] `Goblin Tribal Shields.esp` [Goblin Tribal Shields](https://www.nexusmods.com/oblivion/mods/3242/), [Goblin Tribal Shields fixed](https://www.nexusmods.com/oblivion/mods/11871/)
 - [x] `GodStatues.esp` [GodStatues](https://www.nexusmods.com/oblivion/mods/20001/)
 - [x] `GodStatues KOTN Edition.esp` [GodStatues](https://www.nexusmods.com/oblivion/mods/20001/)
 - [x] `Grandmaster of Alchemy.esp` [Grandmaster of Alchemy](https://www.nexusmods.com/oblivion/mods/16441/)
 - [x] `Illusionary Summons.esp` [Illusionary Summons Pack](https://www.nexusmods.com/oblivion/mods/9014/)
 - [x] `ImpIsle Walkabout  XUL.esp` [ImpIsle Walkabout (junglised)](https://www.nexusmods.com/oblivion/mods/41089/)
 - [x] `Jail Break Routes.esp` [Jail Break Escape Routes](https://www.nexusmods.com/oblivion/mods/39385/)
 - [x] `K2_Summons.esp` **No Source**
 - [x] `Kosai's Welkynd Armor.esp` [HGEC Agea Karan Armor](https://www.nexusmods.com/oblivion/mods/25759/)
 - [x] `LastUnicorn.esp` [Last Unicorn](https://www.nexusmods.com/oblivion/mods/7514/)
 - [x] `Legendary Abilities-Fortify Health MOJ.esp` [Legendary Abilities](https://www.nexusmods.com/oblivion/mods/19245/)
 - [x] `Legendary Abilities-Reflect MOJ.esp` [Legendary Abilities](https://www.nexusmods.com/oblivion/mods/19245/)
 - [x] `Legendary Abilities-Shield MOJ.esp` [Legendary Abilities](https://www.nexusmods.com/oblivion/mods/19245/)
 - [x] `Legion Faction Mod.esp` [Imperial Legion Faction Mod Beta](https://www.nexusmods.com/oblivion/mods/19591/)
 - [x] `Leviathan Soulgems.esp` [Leviathan Soulgems](https://www.nexusmods.com/oblivion/mods/10403)
 - [x] `Marg Lena V5.esp` [Companion Margarete Lena V5 WIP (NSFW)](https://www.loverslab.com/topic/1462-companion-margarete-lena-v5-wip/) Has to be downloaded from a [MediaFire link](https://www.mediafire.com/file/jw78x89x3jxdjiy/Marg_Lena_V5.esp/file), may be worth dropping entirely
 - [x] `Moriarcis.esp` [Moriarcis - City of the Dead](https://www.nexusmods.com/oblivion/mods/17479)
 - [x] `Natural_Vegetation_by_Max_Tael.esp` [Natural Environments](https://www.nexusmods.com/oblivion/mods/2536)
 - [x] `No psychic guards v1.2.esp` [NO PSYCHIC GUARDS 12](https://www.nexusmods.com/oblivion/mods/11911)
 - [x] `Passive Mudcrabs 1.esp` [Passive Mudcrabs](https://www.nexusmods.com/oblivion/mods/16409)
 - [x] `PersonalPackGuars.esp` [PersonalPackGuars](https://www.nexusmods.com/oblivion/mods/20358)
 - [x] `Pitcher Plant and Lily Ingredients.esp` [Pitcher Plant and Lily Ingredients](https://www.nexusmods.com/oblivion/mods/15609)
 - [x] `PJs Spell Compendium - Spell Requirements.esp` [PJsSpellCompendium](https://www.nexusmods.com/oblivion/mods/3892)
 - [x] `Recastable Summons.esp` [Recastable Summons](https://www.nexusmods.com/oblivion/mods/3085)
 - [x] `SecretsoftheAyleidsClosure.esp` [Secrets of the Ayleids Closure](https://www.nexusmods.com/oblivion/mods/22918)
 - [x] `Secure Guild Chest.esp` [Secure Guild Chest](https://www.nexusmods.com/oblivion/mods/16033)
 - [x] `SeductiveIdles.esp` [Seductive Idles](https://www.nexusmods.com/oblivion/mods/11105)
 - [x] `SetsunaDummyTraining.esp` [Setsuna Dummy Training](https://www.nexusmods.com/oblivion/mods/27259) Update with same plugin name [here](https://www.nexusmods.com/oblivion/mods/46161)
 - [x] `Shadow Ranger.esp` [Shadow Ranger](https://www.nexusmods.com/oblivion/mods/26723)
 - [x] `Siliane.esp` **No source**
 - [x] `Silj's Martigen's Monster Mod summmon spells and conjuration compendium.esp` **No source**
 - [x] `Sonia.esp` [COMPANION SONIA II](https://www.nexusmods.com/oblivion/mods/11684) Update with same plugin name [here](https://www.nexusmods.com/oblivion/mods/13017)
 - [x] `Soolie'sBetterEnchantmentEffects.esp` [Soolies Better Enchantment Effects](https://www.nexusmods.com/oblivion/mods/30489)
 - [x] `SPS.esp` [SPS - Simple Prostitution System](https://www.nexusmods.com/oblivion/mods/19697)
 - [x] `Sutch reborn Lighthouse Fix UL.esp` [Sutch Reborn Lighthouse Fix](https://www.nexusmods.com/oblivion/mods/27097)
 - [x] `TheTangMo.esp` [Tang Mo Race](https://www.nexusmods.com/oblivion/mods/5158)
 - [x] `Tombstone Epitaphs.esp` [Tombstone Epitaphs](https://www.nexusmods.com/oblivion/mods/23680) Hidden
 - [x] `Tyrael Companion.esp` [Tyreal Companion](https://www.nexusmods.com/oblivion/mods/23136)
 - [x] `undercover.esp` [Undercover](https://www.nexusmods.com/oblivion/mods/12077) Update with same plugin name [here](https://www.nexusmods.com/oblivion/mods/19913)
 - [x] `Verwen Brewery UL_AY_AC Compatable.esp` [Verwen Brewery - A Village of the Blue Road](https://www.nexusmods.com/oblivion/mods/19892)
 - [x] `Vtoy.esp` [Claudia s little secret The complete story and GOLD EDITION](https://www.nexusmods.com/oblivion/mods/33863)
 - [x] `Wayshrines Improved.esp` [Wayshrines Improved](https://www.nexusmods.com/oblivion/mods/15999)
 - [x] `Wiedergaenger Race.esp` [Wiedergaenger Race REANIMATED EV DV](https://www.nexusmods.com/oblivion/mods/39801)
 - [x] `Wizard'sSpellBook.esp` [Wizards Spell Book](https://www.nexusmods.com/oblivion/mods/20977)
 - [x] `WNewShockBoltEffects20.esp` [Kals New Shock Lightning Spell Effects_v20](https://www.nexusmods.com/oblivion/mods/10239)
 - [x] `WNewShockFunnelEffects20.esp` [Kals New Shock Lightning Spell Effects_v20](https://www.nexusmods.com/oblivion/mods/10239)
 - [x] `Wolf Companions -TcS-.esp` [A Double Wolf Companion -TcS-](https://www.nexusmods.com/oblivion/mods/32921)
 - [x] `Wolvmans_Hidden_Unique_Merchant_Items.esp` [Hidden Unique Merchant Items](https://www.nexusmods.com/oblivion/mods/11847)
 - [x] `xxJump.esp` **No source**

_Originally posted by @MacSplody in https://github.com/loot/oblivion/issues/245#issuecomment-917684966_

**Comment by MacSplody** [comment]
I'll move any that were found over to https://github.com/loot/oblivion/issues/435.

**Comment by sibir-ine** [comment]
I'll remove the unavailable ones in a moment.
