### ISSUE TITLE
'Av Latta Magicka - Rebalance Complete.esp' needs to load after 'Oblivion Content Restoration Project.esp'

### ISSUE THREAD

**Issue by Sabre142** [loot/oblivion#446]
Mod links:
[Av Latta Magicka - Oblivion Magic Overhaul](https://www.nexusmods.com/oblivion/mods/49096)
[Oblivion Content Restoration Project](https://www.nexusmods.com/oblivion/mods/45909)

'Av Latta Magicka - Rebalance Complete.esp' needs to load after 'Oblivion Content Restoration Project.esp' in LOOT. Otherwise, the potion effects will be wrong, since LOOT automatically sorts 'Oblivion Content Restoration Project.esp' after it.

Here is a comparison for the record 000984A6:

'Oblivion Content Restoration Project.esp' loading after 'Av Latta Magicka - Rebalance Complete.esp' (this is the default LOOT sorting behaviour):
![Before](https://user-images.githubusercontent.com/26516348/133371995-f0f4a3ee-930b-452b-acd9-c30d7efcca04.jpg)

'Av Latta Magicka - Rebalance Complete.esp' loading after 'Oblivion Content Restoration Project.esp' (potion effects correctly merged into the bashed patch):
![After](https://user-images.githubusercontent.com/26516348/133372011-78226723-ab81-48da-9c3e-8aeb80caffec.jpg)

I assume the same treatment is required for the modular Av Latta Magicka - Potion Rebalance.esp.

**Comment by MacSplody** [comment]
Okay, I'll add a load after rule for that.

> I assume the same treatment is required for the modular Av Latta Magicka - Potion Rebalance.esp.

No, LOOT sorts the modular files after `Oblivion Content Restoration Project.esp` by default.

![image](https://user-images.githubusercontent.com/1944639/133427730-f39895af-3c6e-434f-bd8c-94f352efb10e.png)
