### ISSUE TITLE
Plugins without a source location

### ISSUE THREAD

**Issue by MacSplody** [loot/oblivion#47]
- [x] `EnhancedWeatherSIOnly.esm` Not hosted on original modpage [Enhanced Weather](https://www.nexusmods.com/oblivion/mods/16544)
- [x] `xeoex.esm`
- [x] `Silgrad_Tower.esm` Not hosted on original modpage [Silgrad Tower v4 beta](https://www.nexusmods.com/oblivion/mods/37132), mirror for [v1.5.7](https://www.gamefront.com/files/silgrad-tower-part-1-plugin-files/download) is just a corrupt archive. [Possibly working](https://www.fileplanet.com/archive/p-21433/Elder-Scrolls-IV-Oblivion-Silgrad-Tower-Full)
- [x] `x117race.esp`
- [x] `Chocolate Elves.esm` by XiNAVRO. `.esp` version is [here](https://www.nexusmods.com/oblivion/mods/18247)
- [x] `Independent High Elf Body (Replace)(v1.1).esm`
- [x] `p2p'sAshDraconian.esm`
- [x] `xeosp++.esp` Not sure if this _LL_ link can be used as it just links to mega. ([nsfw](https://www.loverslab.com/topic/15185-xeo-sp/))
- [x] `xeoexpeople.esp`
- [x] `Qarls_Harvest addon_OOO.esp`
- [x] `bgScriptEffectSilencer.esp`
- [x] `MWakeMap.esp`
- [x] `FCOM_Archery_Armamentarium.esp`
- [x] `FCOM_Archery_Artifacts.esp`
- [x] `FCOM_Archery_RealSwords.esp`
- [x] `FCOM_Archery_MMM_H&C.esp`
- [x] `FCOM_Archery_Deadly.esp`
- [x] `FCOM_Archery_Deadly_Armamentarium.esp`
- [x] `FCOM_Archery_Deadly_RealSwords.esp`
- [x] `FCOM_Archery_Deadly_Artifacts.esp`
- [x] `FCOM_Archery_4_Arma_Complete_patch.esp`
- [x] `FCOM_Hentai Mania.esp` https://www.nexusmods.com/oblivion/mods/33339
- [x] `FCOM_SlofsHorses.esp` https://www.nexusmods.com/oblivion/mods/36679
- [x] `Universitum Arcanorum.esp`
- [x] `John's Leveled List Overhaul.esm`
- [x] `Mein Elfengarten-Bezirk Haus V. 2.0 mit Dachgarten.esp`
- [x] `Mein Elfengarten-Bezirk Haus V. 2.0 OHNE Dachgarten.esp`
- [x] `FalkreathGS_RM.esp` [Gweden Brothel](https://www.nexusmods.com/oblivion/mods/26346)
- [x] `wow.esp`
- [x] `Queen's Sword.esp`
- [x] `R18PN - Bikini Re-Textured.esp`
- [x] `icearmor.esp`
- [x] `Happyhannah''s Wines.esp`
- [x] `Intelligent Learning.esp`
- [x] `AL_MonsterRevisited v1.0.esp`
- [x] `HrmnsOblivionScriptOptimizationv1.0.esp`
- [x] `HrmnsOblivionScriptOptimizationv SI 1.0.esp`
- [x] `TRoN.esp` The Underdark - The Realm Of Northdark
- [x] `Tamriel NPCs Revamped.esp` It might not exist, all other TNR modules use the `TNR` prefix.
- [x] `Traduccion Mejorada Oblivion Clan DLAN.esp`
- [x] `fixterms1C_03.esp` `fixtext1C_04.esp`
- [x] `JJR''sWhiskers and Eyebrow.esp` Deleted from Nexus, no other source http://www.gamesas.com/jazzjr-mods-t82424.html
- [x] `EyelashesVanillaRaces.esp` possibly a duplicate of [EyelashesVannilaRaces.esp](https://www.nexusmods.com/oblivion/mods/18185)
- [x] `EyelashesForVanillaRaces1.0.esp` Seems to be an old version of [Eyelashes For Vanilla Races](https://www.nexusmods.com/oblivion/mods/24085)
- [x] `Bigger_Dremora.esp` Possibly a duplicate of [Bigger_Dremora-2369.esp](https://www.nexusmods.com/oblivion/mods/2369) with an incorrect name.
- [x] `Khajiit Fix.esp`
- [x] `PlayAurMaz.esp`
- [x] `AMD.esp`
- [x] `AMB.esp`
- [x] `CMAll.esp`, `CMAll2.esp` & `CMAllXenius.esp`
- [x] `tes4-CHS-main.esp`
- [x] `!Oblivion_PL.esp`
- [x] `Icon Overhaul.esp` [Deleted](https://www.nexusmods.com/oblivion/mods/44929)
- [x] `EURN.esp`
- [x] `Oblivion_SI Vwalk Full TNR.esp`
- [x] `Cobl - NPCDiversity - TNR Merge.esp`
- [x] `Better-Horse-Eyes.esp` [No esp](https://www.nexusmods.com/oblivion/mods/2808/)
- [x] `Younger Hotter NPC''s 0.99.esp` [Old](https://www.nexusmods.com/oblivion/mods/5288), [latest](https://www.nexusmods.com/oblivion/mods/18908)
- [x] `Ren''s hair on Young Hot NPCs.esp` 
- [x] `Younger  Women''s_1C Gold.esp`
- [x] `Beautiful Women Vwalk Full.esp`
- [x] `ChangeSomeCyrodiilLadies.esp` Obsolete, newer version [Change Some Cyrodill People](https://www.nexusmods.com/oblivion/mods/47326).
- [x] `Arcana Restored.esp` [Hidden file](https://www.nexusmods.com/oblivion/mods/36811)
- [x] `Beautiful Amazon.esp`
- [x] `Better Faces.esp`
- [x] `BPFace_Oblivion.esp`
- [x] `LD_Patrick_Stewart_Sean_Bean.esp`
- [x] `TolkieneElderElf.esp`
- [x] `OblivionMsg.esp`
- [x] `AtiAAFix.esp`, `AtiAAFix_1C.esp`
- [x] `995-Specular Fix 1.1-TESSource.esp`
- [x] `object_placement.esp`
- [x] `Specular_Fix_1.1.esp`
- [x] `Umbacana_quest_fix-9117.esp`
- [x] `Bow_Reach_Fix.esp`
- [x] `Unofficial Oblivion Patch DV.esp
- [x] `Unofficial Oblivion Patch-mobs.esp`
- [x] `UOPS Additional Changes.esp`
- [x] `USIPS Additional Changes.esp`
- [x] `Unofficial Oblivion Patch-mobs.esp`
- [x] `Obl-IM.esp`
- [x] `Oblivion_Deutsch_v3_2_1.esp`
- [x] `Oblivion_Deutsch_v5_0.esp`
- [x] `Traduccion Mejorada S.I.esp`
- [x] `tes4SI-CHS-alpha.esp`
- [x] `tes4-CHS-book.esp`
- [x] `USIPCutterFix.esp` [Unofficial Shivering Isles Patch - Cutter Fix](https://www.nexusmods.com/oblivion/mods/42196)
- [x] `FIX_Unofficial Shivering Isles Patch_1.4_MOBS_FCOM.esp`
- [x] `Unofficial_Shivering_Isles_Patch_10MOBS.esp`
- [x] `Unofficial Shivering Isles Patch 10MOBS.esp`
- [x] `Unofficial Shivering Isles Patch MOBS.esp`
- [x] `Unofficial_Shivering_Isles_Patch_MOBS.esp`
- [x] `Unofficial Shivering Isles Patch-MOBS.esp`
- [x] `Unofficial Shivering Isles Patch-MOBS-FCOM.esp`
- [x] `S.I.C.A.F.U.I.S.v1.2.esp`
- [x] `SI Public Music.esp`
- [x] `Oblivion Vwalk UOS.esp`
- [x] `CoblDeathFix.esp`
- [x] `Francesco's Dark Seducer Weapons Patch.esp`
- [x] `Francescos Dark Seducer Weapons Patch.esp`
- [x] `FranDarkSeducerWeapFix.esp` [Patches for Frans 4_5b](https://www.nexusmods.com/oblivion/mods/17621)
- [x] `Fran Armor Add-on.esp` [Unofficial Francescos Mod Armor AddOn](https://www.nexusmods.com/oblivion/mods/11483)
- [x] `7roads_screens.esp`
- [x] `Retros Fletching and Imbueing 1.71.esp`
- [x] `Retros Fletching and Imbueing 1.7.1_rus.esp`
- [x] `Loading Screens.esp`
- [x] `LoadingScreensDV.esp`
- [x] `LoadingScreensSI-DV.esp`
- [x] `LoadingScreens_OOO.esp`
- [x] `Floydian1 Loading Screens Compilation.esp`
- [x] `OLS_SE_Skyrim.esp`
- [x] `OLS_SE_SkyrimNT.esp`
- [x] `OLS_SE_Vanilla.esp`
- [x] `OLS_SE_DB.esp`
- [x] `OLS_SE_Framed.esp`
- [x] `BlackLoadNoTip.esp`
- [x] `_darker dungeons.esp`
- [x] `Darker Dungeons.esp`
- [x] `DMP - Darker Dungeons Rus.esp`
- [x] `DMP - Darker Dungeons Rus GoldEdition.esp`
- [x] `Immersive Caves.esp`
- [x] `Immersive Caves Auto.esp`
- [x] `_darker_nights_2_with_burning_kvatch.esp`
- [x] `darker nights for shivering isles.esp`
- [x] `PW_MorrowindFog.esp`
- [x] `Arthur_ Natural weather with HDR.esp`
- [x] `Enhanced Weather - Elsweyr Anequina Patch.esp`
- [x] `EnhancedWeather - Enhanced Seasons.esp`
- [x] `EnhancedWeather - SI.esp`
- [x] `EnhancedWeatherSIOnly.esp`
- [x] `EnhancedWeatherSIOnly.esm`
- [x] `EW-GTA2 Patch.esp`
- [x] `All Natural - Enhanced Weather.esp`
- [x] `All Natural - Natural Weather.esp`
- [x] `All Natural - EW + NW.esp`
- [x] `All Natural - Atmospheric Weather System.esp`
- [x] `All Natural - EW + AWS.esp`
- [x] `All Natural - NW + AWS.esp`
- [x] `All Natural - EW + NW + AWS.esp`
- [x] `All Natural - Enhanced Seasons.esp`
- [x] `All Natural - Debug Ring.esp`
- [x] `All Natural - Weather Inside.esp`
- [x] `All Natural - Optional Features.esp`
- [x] `Gates To Aesgaard Weather Patch.esp`
- [x] `GTAesgaard 1and2 Delayer.esp`
- [x] `GTAesgaard I-II Delayer.esp`
- [x] `Immersive Interiors - Lights Addon.esp`
- [x] `Natural Interiors.esp`
- [x] `no_wind-2578.esp`
- [x] `NoWind.esp`
- [x] `No wind.esp`
- [x] `AdvancedWater.esp`
- [x] `Advanced_Water.esp`
- [x] `More Immersive Sound.esp`
- [x] `al-smm7.esp`
- [x] `al-smm7-ru.esp`
- [x] `Real_Lights.esp`
- [x] `RealLightsDV.esp`
- [x] `OCC-IWR-Patch.esp`
- [x] `aKALAmbientDungeonsBeta2.esp`
- [x] `300_lore dialogue v1.15.esp`
- [x] `AkaviriBattleCat.esp` [Deleted](https://www.nexusmods.com/oblivion/mods/44545)
- [x] `Anvil Dock Map Marker.esp` Incorrect plugin name? [Anvil Docks Map Marker](https://www.nexusmods.com/oblivion/mods/9528) `DocksMapMarker.esp`
- [x] `Automagic Bags 1.1.esp`
- [x] `OBG - Buechermod - Bilder - BP.esp`
- [x] `Bitches of the Duke.esp`
- [x] `Brandy.esp`
- [x] `BPMerchantStorage.esp`
- [x] `BTMoreEnemies.esp`
- [x] `Camera Redone.esp`
- [x] `CATSDeerPeltsAndAntlers.esp`
- [x] `tw1_fov_adjustor.esp`
- [x] `ClocksOfCyrodiilBC.esp`
- [x] `ClocksOfCyrodiilOBC.esp`
- [x] `ClocksOfCyrodiil_BC_OBC_OC_OCLR_Vanilla.esp`
- [x] `OCC-CoC-Patch.esp`
- [x] `Cryptic Festive Ayleid Dining Set.esp`
- [x] `Cryptic Frosted Ayleid Dining Set.esp`
- [x] `Cryptic Blue Blood Ayleid Dining Set.esp`
- [x] `Cryptic Lake View Ayleid Dining Set.esp`
- [x] `Cryptic Snowy Oak Ayleid Dining Set.esp`
- [x] `Cryptic White Rose Ayleid Dining Set.esp`
- [x] `Cryptic Festive Ayleid Dining Set.esp`
- [x] `Cryptic's Buyable Ayleid Dining Sets.esp`
- [x] `CrypticsBuyableAyleidDiningSets_1C.esp`
- [x] `Buyable Ayldeid Dishes.esp`
- [x] `Oblivion_Deutsch_v3_1.esp`
- [x] `Diverse Dungeons - Subtle Color v.1.04.esp` [Deleted](https://www.nexusmods.com/oblivion/mods/10466)
- [x] `Energy - Bandits.esp`
- [x] `Inebriation Rus.esp`
- [x] `Extended Death Camera.esp`
- [x] `Fatality Cam.esp`
- [x] `archrobe.esp` https://www.nexusmods.com/oblivion/mods/16941

**Comment by Ortham** [comment]
Enhanced Weather is one of mine - IIRC the SI only .esm file is obsolete, as newer versions control where the weather is controlled through a config file.

**Comment by MacSplody** [comment]
> 
> Enhanced Weather is one of mine - IIRC the SI only .esm file is obsolete, as newer versions control where the weather is controlled through a config file.

Okay thanks. So `EnhancedWeatherSIOnly.esm` was on the [Enhanced Weather](https://www.nexusmods.com/oblivion/mods/16544) modpage at some point.
